feat(testing): Port infinite task sender to rust.
yetanotherco/aligned_layer pull request #1040
Opened 2024-09-20 12:55 UTC by PatStiles

Closes #1015 creates a rust cli tool to generate and submit infinite task to the network to replace the current shell scripting framework.

TODO:
- [x] Test locally.
- [ ] Test on Holesky with local Keystore.

2024-09-26 15:35 UTC, uri-99 commented on batcher/aligned/src/main.rs
> +async fn get_user_balance(
why this change?

2024-09-26 15:36 UTC, uri-99 commented on batcher/aligned-task-sender/src/main.rs
> +//TODO: Duplicated from `batcher/aligned`.
remove TODO

2024-09-26 15:36 UTC, uri-99 commented on batcher/aligned-task-sender/src/main.rs
> +            //TODO: sort out error messages
solve TODO

2024-09-26 22:19 UTC, uri-99 commented on batcher/aligned-task-sender/src/main.rs
> +    }
this will change after #1005 is merged

2024-09-26 22:20 UTC, uri-99 requested changes
Temporarily blocking PR, leaving some comments and also it should be merged after #1005

2024-09-26 22:29 UTC, uri-99 commented on batcher/aligned-task-sender/src/main.rs
> +        SendInfinite(submit_args) => {
We are planning on adding some more variations, right?

2024-09-26 22:37 UTC, uri-99 commented on batcher/aligned-task-sender/src/main.rs
> +            let chain_id = get_chain_id(eth_rpc_url.as_str()).await.map_err(|e| {
It would be cleaner to use `get_chain_id` from the SDK

2024-09-26 23:25 UTC, uri-99 commented on batcher/aligned-task-sender/src/main.rs
> +        long = "batcher_url",
we have been using `kebab-case` for parameters

2024-09-30 21:59 UTC, closed without merging

2024-09-30 21:59 UTC, PatStiles commented
Will close and reopen