refactor: remove check in BatcherPaymentService
yetanotherco/aligned_layer pull request #1064
Opened 2024-09-24 13:23 UTC by MarcosNicolau

**Changes**
This PR removes the check for zero addresses in the recovered signature within the `BatcherPaymentService` contract. The library handling the signature recovery already performs this check when splitting the fields (`r`, `v`, `s`) first and then calling the `ecrecover` precompile, where it does the check (see [here](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/dbb6104ce834628e473d2173bbc9d47f81a9eec3/contracts/utils/cryptography/ECDSA.sol#L142-L145)). 

**Testing**
I've tested that everything works by setting up a local environment and sending some `sp1` and `plonk` proofs. Here is the process:

1. Start aggregator: `make aggregator_start`.
2. Start operator: `make operator_register_and_start`.
3. Start batcher: `make batcher_start_local`.
4. Send some proofs and make sure everything works as expected.

Closes #1061

2024-09-24 16:20 UTC, entropidelic approved these changes

2024-09-24 19:29 UTC, MauroToscano requested changes
Re-deploy aligned contracts and test it, and push them

2024-09-24 19:30 UTC, uri-99 approved these changes

2024-09-25 15:57 UTC, MauroToscano approved these changes

2024-09-25 15:57 UTC, merged