1006 remove batcher duplicated code when handling nonpaying
yetanotherco/aligned_layer pull request #1066
Opened 2024-09-24 15:33 UTC by MarcosNicolau

2024-09-24 17:17 UTC, MarcosNicolau commented on batcher/aligned-batcher/src/lib.rs
> +            if user_balance == U256::from(0) {
I don't understand why here we check if the balance is zero instead of checking for the actual cost of the verification.

2024-09-24 17:19 UTC, MarcosNicolau commented on batcher/aligned-batcher/src/lib.rs
> +    ) -> bool {
This function can never fail, but the return of the boolean is just to keep the consistency with the other methods and to account for a future failing point. Please tell me if I should better remove it.

2024-09-24 17:26 UTC, Oppen commented on batcher/aligned-batcher/src/lib.rs
> +            if user_balance == U256::from(0) {
I think this is because it's a non-paying message, so there isn't any particular balance the user needs to reach, as long as it's not empty. If that's the case, it's worth a code comment.

2024-09-26 17:13 UTC, uri-99 requested changes
Blocking PR until Entropidelic's refactor is pushed

2024-10-03 20:30 UTC, uri-99 commented
Closing as solved in #1106

2024-10-03 20:30 UTC, closed without merging