feat(contracts): Use block timestamp instead of block number.
yetanotherco/aligned_layer pull request #1085
Opened 2024-09-25 15:09 UTC by PatStiles

closes: #1069

Switches the userData to check and return in events the block timestamp instead of block number.

## To Test:
- [x] `anvil_deploy_aligned_contracts` and `anvil_start_with_block_time`
- [x] Run local testnet and ensure nothing errors.

2024-09-25 15:57 UTC, Oppen approved these changes

2024-09-26 15:06 UTC, MauroToscano requested changes
New JSON of contracts should be pushed. Also, it needs to have in the description how it should be tested. It can include changing the time for something smaller like 45 seconds just to check really quick

2024-09-27 18:29 UTC, MarcosNicolau approved these changes
I tested it with `cast` running the following commands:
1. Fund account: `cast send --value 100000 0x7969c5eD335650692Bc04293B07F5BF2e7A673C0  --from <ADDRESS>  --private-key <PK> --rpc-url "http://localhost:8545"`
 cast send 0x7969c5eD335650692Bc04293B07F5BF2e7A673C0  "unlock()" --rpc-url http://localhost:8545 --private-key <PK> --from <ADDRESS>
2. Unlock to withdraw: ` cast send 0x7969c5eD335650692Bc04293B07F5BF2e7A673C0  "unlock()" --rpc-url http://localhost:8545 --private-key <PK>  --from <ADDRESS> `
3. Advance `anvil` seconds to not wait: 
```bash
curl http://localhost:8545 \
  -X POST \
  -H "Content-Type: application/json" \
  --data '{"jsonrpc":"2.0","method":"evm_increaseTime","params":[2000],"id":1}'
```
5. And now you should be able to withdraw: `cast send 0x7969c5eD335650692Bc04293B07F5BF2e7A673C0  "withdraw(uint256)" 10000 --rpc-url http://localhost:8545 --private-key 0x2a871d0798f97d79848a013d4936a73bf4cc922c825d33c1cf7073dff6d409c6      
`

And checking the `BalanceUnlocked` data when doing `unlock` returns the correct timestamp.

It seems that it works as expected.

2024-09-27 21:08 UTC, IAvecilla approved these changes

2024-09-27 21:08 UTC, IAvecilla commented on contracts/src/core/BatcherPaymentService.sol
> +    error FundsLocked(uint256 unlockBlock, uint256 currentBlockTime); // bedc4e5a
I think that the first parameter `unlockBlock` should also change to `unlockBlockTime`

2024-09-27 21:08 UTC, IAvecilla commented on contracts/src/core/BatcherPaymentService.sol
> +        userData[msg.sender].unlockBlockTime = 0;
This is more of a general question about the `unlock/lock` flow: we are not preventing a user from repeatedly calling unlock and lock, which would reset their `unlockBlockTime`. Should we consider preventing that scenario? It might be possible for a user to accidentally reset the timer, and it could be helpful to add some checks before allowing that, from what I understand a check `unlockBlockTime == 0` for the unlock would be sufficient. This seems beyond the scope of this PR, but it may be worth considering for the future.

2024-09-27 22:25 UTC, JuArce commented
Deployed in stage

2024-09-27 22:39 UTC, MauroToscano approved these changes

2024-09-27 22:39 UTC, merged