chore(deps): bump go eigensdk to 0.1.12
yetanotherco/aligned_layer pull request #1088
Opened 2024-09-25 17:54 UTC by MarcosNicolau

**Changes**
Updates go eigensdk to version 0.1.12 which fixes the double signature err. All files using the SDK have been updated accordingly to the new version.

2024-09-26 18:17 UTC, MauroToscano requested changes
- Default config of operator not registering

2024-09-26 19:49 UTC, MarcosNicolau commented
> * Default config of operator not registering

Fixed! We needed to wait for the receipt when depositing into the strategy contract. Tbh, I don't know why it was working with the rest of the configurations.

2024-09-30 17:13 UTC, PatStiles approved these changes
Warn observed LGTM

2024-10-01 18:22 UTC, entropidelic approved these changes

2024-10-01 18:24 UTC, MauroToscano approved these changes

2024-10-01 18:25 UTC, merged