fix(contracts): check address are not zero in initialization
yetanotherco/aligned_layer pull request #1094
Opened 2024-09-25 22:04 UTC by MarcosNicolau

**Changes**
This pr adds checks to make sure addresses are not zero while initializing the contracts.

Closes #1020

2024-09-27 17:46 UTC, PatStiles approved these changes

2024-09-27 18:14 UTC, JuArce requested changes

2024-09-27 18:14 UTC, JuArce commented on contracts/src/core/AlignedLayerServiceManager.sol
There are missing the validation in the constructor
```
IAVSDirectory __avsDirectory,
IRewardsCoordinator __rewardsCoordinator,
IRegistryCoordinator __registryCoordinator,
IStakeRegistry __stakeRegistry
```
Those are addresses too

2024-09-27 18:21 UTC, uri-99 requested changes
Every time any contract changes, we should push the new anvil-state to make sure we can simply run `make anvil_start` on a branch and know we are dealing with the current branch's contracts.

For this, you must push the `.json` file generated when running `make anvil_deploy_aligned_contracts`

2024-09-27 19:14 UTC, MarcosNicolau commented on contracts/src/core/AlignedLayerServiceManager.sol
Solved!

2024-09-27 19:59 UTC, IAvecilla approved these changes

2024-09-27 20:33 UTC, uri-99 approved these changes

2024-09-27 21:10 UTC, PatStiles approved these changes

2024-09-30 19:51 UTC, JuArce approved these changes

2024-09-30 19:52 UTC, merged