refactor(contracts): remove merkle root and signature checks on payment service contract
yetanotherco/aligned_layer pull request #1114
Opened 2024-09-30 18:07 UTC by MarcosNicolau

**Changes**
Remove the merkle root and signature checks to save on gas in the payment service contract.

**Tests**
[WIP]

2024-09-30 21:43 UTC, uri-99 requested changes
We can still remove the usage of `nonce` and `maxFee` from the contracts to make it cheaper, `ProofSubmitterData` can be only the address

2024-09-30 21:48 UTC, MarcosNicolau commented
> We can still remove the usage of nonce and maxFee from the contracts to make it cheaper, ProofSubmitterData can be only the address

Updated!

2024-09-30 22:22 UTC, uri-99 requested changes

2024-09-30 22:22 UTC, uri-99 commented on contracts/src/core/BatcherPaymentServiceStorage.sol
if `ProofSubmitterData` is going to be only 1 address, it should be quite cheaper to just pass the address. It will save reading/writing inside the struct.

2024-10-01 13:06 UTC, MarcosNicolau commented on contracts/src/core/BatcherPaymentServiceStorage.sol
Updated!

2024-10-02 23:44 UTC, uri-99 requested changes

2024-10-02 23:44 UTC, uri-99 commented on contracts/src/core/BatcherPaymentService.sol
>          address signer,
it is no longer a signer

2024-10-02 23:44 UTC, uri-99 commented on contracts/src/core/BatcherPaymentService.sol
remove unused errors
`NoLeavesSubmitted`
`NotEnoughLeaves`
etc.

refactor to appropriate new names:
`NoProofSubmitterSignatures`
etc.

2024-10-02 23:44 UTC, uri-99 commented on contracts/src/core/BatcherPaymentService.sol
remove EIP712 related things, since it is for signatures

2024-10-02 23:44 UTC, uri-99 commented on contracts/src/core/BatcherPaymentService.sol
remove user_nonces

2024-10-02 23:44 UTC, uri-99 commented on contracts/src/core/BatcherPaymentService.sol
remove `noncedVerificationDataTypeHash` things

2024-10-03 20:20 UTC, uri-99 approved these changes

2024-10-03 22:09 UTC, uri-99 requested changes

2024-10-03 22:09 UTC, uri-99 commented on contracts/src/core/BatcherPaymentServiceStorage.sol
update GAP size

2024-10-08 15:16 UTC, uri-99 requested changes
needs changes on docs

2024-10-08 22:07 UTC, entropidelic commented
@uri-99 I updated the docs in [docs/2_architecture/components/2_payment_service_contract.md](https://github.com/yetanotherco/aligned_layer/pull/1114/files#diff-79cfd0b19de5a783364b561762e20f58bedb3fda8f92235523f6036f7d3ae336)

2024-10-08 22:07 UTC, entropidelic approved these changes

2024-10-09 17:26 UTC, uri-99 approved these changes

2024-10-09 17:35 UTC, merged