fix: add dependencies that vary depending on the os to make deps
yetanotherco/aligned_layer pull request #117
Opened 2024-05-03 20:46 UTC by NicolasRampoldi

# Description
- `make deps` now installs necessary submodules and build all the FFIs depending on the OS.
- `make go_deps` now installs Go dependencies (zap-pretty, abigen, eigenlayer-cli).
- TODO: this should be tested in Linux.

2024-05-03 21:52 UTC, uri-99 requested changes

2024-05-03 21:52 UTC, uri-99 commented on Makefile
> +	YQ_INSTALL_CMD = sudo apt-get install yq
there is no apt-get yq
```suggestion
	YQ_INSTALL_CMD = brew install yq
```

2024-06-03 18:00 UTC, MauroToscano approved these changes

2024-06-03 18:10 UTC, jotabulacios approved these changes
lgtm

2024-06-03 18:21 UTC, merged