fix: add panic catch on operator calling FFI
yetanotherco/aligned_layer pull request #1196
Opened 2024-10-07 22:05 UTC by JulianVentura

### Motivation

We have some calls to external Rust functions on operator Golang code. If any of those functions panics, that error is propagated to the golang application and it fails completly. We want to catch those errors so this doesn't happen.

### Changes

* Add golang panic handling with `recover()` on `VerifySp1Proof`.
* Add a function wrapper with a `catch_unwind` from Rust side for `verify_sp1_proof_ffi`.
* Modify `verify_sp1_proof_ffi` to return `i32` instead of `bool` to inform about errors.

### How to test

In order to check the fix, you should first make it crash by adding a `panic!()` inside the `verify_sp1_proof_ffi` function on `sp1/lib/src/lib.rs`. It's recommended to do that on staging branch.

In order to run, you should:

1. Execute anvil: 
  - `make anvil_start_with_block_time`
3. Launch aggregator: 
  - `make aggregator_start`
5. Launch operator: 
  - `make build_operator`
  - `make operator_full_registration CONFIG_FILE=config-files/config-operator-1.yaml`
  - `./operator/build/aligned-operator start --config ./config-files/config-operator-1.yaml`
6. Launch batcher:
  - `make batcher_start_local`
7. Start sending tx with
  - `make batcher_send_infinite_sp1`

Operator should stop executing showing a panic from rust execution.

Now, you can switch to `fix/operator-ffi-panic-catch` branch and repeat the process. Don't forget to add the panic inside the `inner_verify_sp1_proof_ffi`. You should see some errors being logged in the operator, but it should keep executing without any crashes.

2024-10-09 19:00 UTC, MarcosNicolau requested changes
I tested on macos and go still panics. Have you rebuilt the ffis after every change?

2024-10-09 19:00 UTC, MarcosNicolau commented on Makefile
> +batcher_send_risc0_big_burst:
You can use the current target `batcher_send_risc0_burst` and provide a `BURST_SIZE=100`

2024-10-09 20:28 UTC, JuArce commented
Would be nice a review from @Oppen

2024-10-10 18:26 UTC, PatStiles commented
This sucessfully caught panics for the merkle tree verification and sp1 verification but failed when I tested with risc0.

2024-10-16 19:59 UTC, JulianVentura commented on Makefile
> +batcher_send_risc0_big_burst:
Done!

2024-10-16 19:59 UTC, JulianVentura commented
> I tested on macos and go still panics. Have you rebuilt the ffis after every change?
> 
> I might have tested it wrongly, but would you please check If it works on your machine if it does, I'll make sure to try again.

Could you check again, please?

2024-10-16 21:04 UTC, MarcosNicolau approved these changes
It is working for me now! 🚀

2024-10-16 22:58 UTC, Oppen commented on operator/merkle_tree_old/lib/libmerkle_tree.a
This seems to have been committed by accident.

2024-10-16 22:58 UTC, Oppen commented on operator/merkle_tree_old/lib/libmerkle_tree.dylib
This as well.

2024-10-16 23:02 UTC, Oppen approved these changes
Works for me and the code looks good. Just remove the leftover binaries.

2024-10-17 15:54 UTC, PatStiles approved these changes
Caught all panics on a local testnet.

2024-10-18 17:29 UTC, uri-99 approved these changes

2024-10-18 20:03 UTC, merged