chore(dependency): Bump sp1 and risc0 version
yetanotherco/aligned_layer pull request #1208
Opened 2024-10-09 21:17 UTC by PatStiles

closes #1205 

## To Test:
- `make test_risc_zero_go_bindings_macos`
- `make test_sp1_go_bindings_macos`
- run local testnet and confirm you can submit sp1 and risc0 proofs. via
`make batcher_send_risc0_task`
`make batcher_send_sp1_task`
- confirm examples work:
`cd examples/zkquiz/quiz/script && cargo run -r`
`cd examples/validating-public-input/risc_zero/fibonacci_proof_generator && cargo run -r`

2024-10-14 13:33 UTC, MarcosNicolau approved these changes
Tested on my machine.

2024-10-14 17:30 UTC, Oppen reviewed
Looks OK, will test later today.

2024-10-14 19:11 UTC, Oppen approved these changes
Works on my machine.

2024-10-14 20:53 UTC, uri-99 requested changes
Operators should have retrocompatibility. So we should have 2 ffis and each operator check with both

2024-10-17 22:43 UTC, uri-99 requested changes
We don't need to push old proof generators. To test we can checkout previous branch. I would avoid pushing this because this pr is 87 files, and a very big portion of these are the old proof generators

2024-10-18 15:35 UTC, uri-99 requested changes

2024-10-18 15:35 UTC, uri-99 commented on Makefile
> +	export LD_LIBRARY_PATH:=$(CURDIR)/operator/risc_zero_old/lib:$(CURDIR)/operator/risc_zero/lib
so we are exporting both? or only 1?

2024-10-18 15:35 UTC, uri-99 commented on Makefile
> -	@mv scripts/test_files/sp1/fibonacci_proof_generator/script/sp1_fibonacci.proof scripts/test_files/sp1/
why?

2024-10-18 15:35 UTC, uri-99 commented on Makefile
> -	@cp operator/risc_zero/lib/target/$(TARGET_REL_PATH)/librisc_zero_verifier_ffi.dylib operator/risc_zero/lib/librisc_zero_verifier_ffi.dylib
is there a reason for the name change? because now linux has _ffi and mac doesn't. I would try to keep both the same

2024-10-18 15:35 UTC, uri-99 commented on Makefile
> +	echo $(LD_LIBRARY_PATH)
remove? looks like debugging

2024-10-18 15:35 UTC, uri-99 commented on Makefile
> +test_risc_zero_rust_ffi_old:
is this normal?
<img width="943" alt="image" src="https://github.com/user-attachments/assets/c8d89bb6-0b9a-4632-9aba-c2b971acb501">

2024-10-18 15:35 UTC, uri-99 commented on operator/risc_zero/risc_zero.go
> +#cgo darwin LDFLAGS: -L./lib -lrisc_zero_verifier
in linux it is still called with _fii

2024-10-18 15:35 UTC, uri-99 commented on examples/zkquiz/quiz/script/src/main.rs
why these changes? I think they might not be related to this PR

2024-10-18 15:35 UTC, uri-99 commented on operator/risc_zero/lib/librisc_zero_verifier.dylib
this file should be in gitignore (the name changed removing the _ffi and the gitignore was not updated)

2024-10-18 15:35 UTC, uri-99 commented on scripts/test_files/risc_zero/risc_zero_fibonacci_old.proof
I would move this file inside `./fibonacci_proof_generator`
so it is right besides `scripts/test_files/risc_zero/fibonacci_proof_generator/risc_zero_fibonacci.proof`

2024-10-18 15:35 UTC, uri-99 commented on scripts/test_files/risc_zero/risc_zero_fibonacci_old.pub
same here, move inside `./fibonacci_proof_generator`
This will make much easier and more reliable the removal of the _old stuff later on.

2024-10-18 15:35 UTC, uri-99 commented on scripts/test_files/risc_zero/risc_zero_fibonacci_old.pub
This refactor will need renaming of some paths around the code (when this file is called)

2024-10-18 15:35 UTC, uri-99 commented on operator/pkg/operator.go
> +		}
```suggestion
		if !verificationResult {
			o.Logger.Infof("Risc0 proof verification failed. Trying old SP1 version...")
			verificationResult = risc_zero_old.VerifyRiscZeroReceiptOld(verificationData.Proof, verificationData.VmProgramCode, verificationData.PubInput)
			if !verificationResult {
				o.Logger.Errorf("Risc0_old proof verification failed")
			}
		}
		o.Logger.Infof("Risc0 proof verification result: %t", verificationResult)
		results <- verificationResult
```

2024-10-18 15:35 UTC, uri-99 commented on operator/pkg/operator.go
> +		}
There is an unsent verificationResult case

```suggestion
		if !verificationResult {
			o.Logger.Infof("SP1 proof verification failed. Trying old SP1 version...")
			verificationResult = sp1_old.VerifySp1ProofOld(verificationData.Proof, verificationData.VmProgramCode)
			if !verificationResult {
				o.Logger.Errorf("SP1_old proof verification failed")
			}
		}
		o.Logger.Infof("SP1 proof verification result: %t", verificationResult)
		results <- verificationResult
```

2024-10-18 16:29 UTC, PatStiles commented on Makefile
> +test_risc_zero_rust_ffi_old:
Can you provide some more context I'm having trouble understanding the issue with the tes
<img width="488" alt="Screenshot 2024-10-18 at 13 29 17" src="https://github.com/user-attachments/assets/ad383baf-dc8f-465b-a517-1272cc49f990">
t. I ran it local and pulling the branch fresh and got

2024-10-18 16:30 UTC, PatStiles commented on examples/zkquiz/quiz/script/src/main.rs
The change from inquire -> dialoguer was necessary to due to an upstream dependency conflict with `thiserror`

2024-10-18 16:33 UTC, PatStiles commented on operator/risc_zero/risc_zero.go
> +#cgo darwin LDFLAGS: -L./lib -lrisc_zero_verifier
Yes, I hit issues with the linker finding the shared library. Even with manually setting the shared library directory https://github.com/yetanotherco/aligned_layer/pull/1208/files#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52R20 the linker was looking for `librisc_zero_verifier_ffi.so` when `librisc_zero_verifier.so` was declared in the go file. Add the `_ffi` fixed this.

2024-10-18 21:17 UTC, uri-99 commented on Makefile
> +test_risc_zero_rust_ffi_old:
Yes, what i mean is that test_verifier_old runs 0 tests? But there are new tests in this PR

2024-10-21 14:40 UTC, MarcosNicolau requested changes
Other than the minor comments, I tested on Linux and everything worked as expected!

<img width="1410" alt="Screenshot 2024-10-21 at 11 39 47 AM" src="https://github.com/user-attachments/assets/fa6003d9-7739-43ef-8e6b-a6ec74747cb8">

2024-10-21 14:40 UTC, MarcosNicolau commented on Makefile
> +	export LD_LIBRARY_PATH:=$(CURDIR)/operator/risc_zero_old/lib:$(CURDIR)/operator/risc_zero/lib
I think this is right. Tough, why did you replace the `+=` with `:=`. When doing `:=` you are replacing the current user value. `+=` appends to the user value. I would leave the `+=` just to make sure we don't break any user setup which might be needed when running ffis.

2024-10-21 14:40 UTC, MarcosNicolau commented on examples/zkquiz/quiz/script/Cargo.toml
> +inquire = "0.7.5"
Is dialoguer not supported by the newer version?

2024-10-21 14:40 UTC, MarcosNicolau commented on operator/risc_zero_old/lib/src/lib.rs
> +pub extern "C" fn verify_risc_zero_receipt_old_ffi(
You should add the `try-catch`.

2024-10-21 14:40 UTC, MarcosNicolau commented on operator/risc_zero_old/lib/src/lib.rs
> +pub extern "C" fn verify_risc_zero_receipt_old_ffi(
See #1174.

2024-10-21 14:40 UTC, MarcosNicolau commented on operator/sp1_old/lib/src/lib.rs
> +pub extern "C" fn verify_sp1_proof_old_ffi(
Ditto.

2024-10-21 14:40 UTC, MarcosNicolau commented on Makefile
> +test_risc_zero_rust_ffi_old:
In my case, I ran them on Linux and they worked.

2024-10-21 19:46 UTC, MarcosNicolau commented on operator/risc_zero/lib/librisc_zero_verifier.dylib
I think you uploaded this by err.

2024-10-21 19:46 UTC, MarcosNicolau commented on operator/risc_zero_old/lib/src/lib.rs
> +pub extern "C" fn verify_risc_zero_receipt_old_ffi(
If it is too much work now, maybe don't.

2024-10-22 18:13 UTC, PatStiles commented
@MarcosNicolau @uri-99 I am closing this in favor or #1307 due to merge issues

2024-10-22 18:13 UTC, closed without merging