feat: add gas price to prometheus
yetanotherco/aligned_layer pull request #1257
Opened 2024-10-15 13:53 UTC by avilagaston9

**Motivation**

This PR creates a new Grafana dashboard with a panel that shows the gas_price of every block.

**Description**

- Creates a new Grafana dashboard.
- Fetches the `gas_price` from the net into the Elixir tracker every 12 seconds.
- Enables the `/metrics` endpoint with the new metric.
- Adds the new target to the Prometheus config.

Closes #1244 

## To Test
```
make anvil_start_with_block_time
```
```
make telemetry_create_env
make telemetry_start
```
```
make run_metrics
```
Access to the new `Ethereum` dashboard at `http://localhost:3000`.
And then you can run transactions and visualize gas costs variations. 
You can also set the `RPC_URL` env variable on `telemetry_api/.env` to a holesky RPC and visualize real time testnet gas costs.

<img width="704" alt="image" src="https://github.com/user-attachments/assets/c9c816a3-04c5-40d8-8f09-ce7067cc884a">

2024-10-15 17:42 UTC, uri-99 commented on telemetry_api/lib/telemetry_api/periodically.ex
> +    :timer.send_interval(one_second * 12, :gas_price) # every 12 seconds, once per block
I would recommend once per 10 seconds, for redundancy, as not every block is exactly 12 seconds.

```suggestion
    :timer.send_interval(one_second * 10, :gas_price) # every 10 seconds, once per block with a bit of some margin
```

2024-10-15 18:37 UTC, uri-99 approved these changes

2024-10-16 02:35 UTC, JuArce requested changes
You are trying to merge it to testnet. It may be wrong

2024-10-16 02:37 UTC, JuArce requested changes

2024-10-16 02:37 UTC, JuArce commented on prometheus/prometheus.yaml
> +      - targets: [ "host.docker.internal:4001" ]
I think it is a bad idea to scrap to the same port where the API es served. It should another one

2024-10-17 15:01 UTC, MarcosNicolau approved these changes
Code LGTM, tested on my machine!

2024-10-18 01:11 UTC, entropidelic commented on telemetry_api/lib/telemetry_api/periodically.ex
> +    :timer.send_interval(one_second * 10, :gas_price) # every 10 seconds, once per block + some margin
maybe the sampling rate can be defined as a constant somewhere

2024-10-18 01:20 UTC, entropidelic commented
lgtm, maybe we should start using some logging library instead of the `IO.inspect`s but not really important right now

2024-10-18 01:20 UTC, entropidelic approved these changes

2024-10-18 13:44 UTC, JuArce approved these changes

2024-10-18 14:34 UTC, merged