Recalculate proof max fee and nonce
yetanotherco/aligned_layer pull request #1313
Opened 2024-10-23 20:43 UTC by gabrielbosio

# Recalculate proof max fee and nonce

## Description

Enforces max fee of proof `n` to be less or equal than max fee of proof `n-1`.
Allows proof nonce to be optional. If no value is passed, the Batcher uses `user_nonce + 1` where `user_nonce` is the nonce mapped for the user address in Ethereum. 

## Type of change

New feature

## Checklist
- [ ] Linked to Github Issue
- [ ] This change depends on code or research by an external entity
  - [ ] Acknowledgements were updated to give credit
- [ ] Unit tests added
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.
- [ ] This change is an Optimization
  - [ ] Benchmarks added/run
- [ ] Has a known issue
  - [Link to the open issue addressing it]()

2024-11-05 21:48 UTC, JulianVentura requested changes
Code looks fine, but I had a "Failed to deserialize" error message when I tried to send an sp1 task to test.
I had to merge from staging in order to run anvil, so that may be breaking something

2024-11-07 19:38 UTC, avilagaston9 commented on docs/3_guides/1.2_SDK_api_reference.md
>  Returns the nonce to use for a given address.
```suggestion
Returns the nonce for a given address in Ethereum from aligned payment service contract.
Note that it might be out of sync if you recently sent proofs. For that see [`get_nonce_from_batcher`](#get_nonce_from_batcher)
```

2024-11-07 19:41 UTC, avilagaston9 commented on docs/3_guides/1.2_SDK_api_reference.md
> +# Arguments
```suggestion
#### Arguments
```

2024-11-07 19:41 UTC, avilagaston9 commented on docs/3_guides/1.2_SDK_api_reference.md
> +# Returns
```suggestion
#### Returns
```

2024-11-07 19:41 UTC, avilagaston9 commented on docs/3_guides/1.2_SDK_api_reference.md
> +# Errors
```suggestion
#### Errors
```

2024-11-07 19:44 UTC, avilagaston9 commented on docs/3_guides/1.2_SDK_api_reference.md
> +
```suggestion
as the batcher proofs might not yet be on ethereum, producing an out-of-sync nonce with the payment service contract on ethereum

```rust
pub async fn get_nonce_from_batcher(
    batcher_ws_url: &str,
    address: Address,
) -> Result<U256, GetNonceError> {
```
```

2024-11-07 19:54 UTC, avilagaston9 commented on docs/3_guides/1.2_SDK_api_reference.md
>  ) -> Result<ethers::types::TransactionReceipt, errors::PaymentError> {
This code should be wrapped in a Rust code block like this:
```Rust
pub async fn deposit_to_aligned(
amount: U256,
signer: SignerMiddleware<Provider<Http>, LocalWallet>,
network: Network,
) -> Result<ethers::types::TransactionReceipt, errors::PaymentError> {

2024-11-07 21:39 UTC, JulianVentura approved these changes
Working fine, good job!

2024-11-08 13:51 UTC, PatStiles approved these changes
Tested locally and works great!

2024-11-11 22:04 UTC, uri-99 approved these changes

2024-11-11 23:19 UTC, merged