feat(batcher): Update SP1 and Risc0 version in batcher, examples, and docs
yetanotherco/aligned_layer pull request #1329
Opened 2024-10-25 18:02 UTC by PatStiles

# Update Batcher SP1 and Risc0 version

## Description

Complements #1324 
Updates the SP1 and Risc0 version in the:
- batcher
- examples
- docs
Renames the test files for SP1 and Risc0 by changing the respective suffix to point towards the correct version ("" indicates removal of the suffix):
"_new" -> ""
"" -> "-> old

NOTE: Removal of the old verifier ffi bindings will occur in a third pr.

## Type of change

- [x] New feature

2024-10-25 21:23 UTC, entropidelic commented on docs/3_guides/4_generating_proofs.md
> +  Make sure to have [Risc0](https://dev.risczero.com/api/zkvm/quickstart#1-install-the-risc-zero-toolchain) installed with version `v1.1.2`
we should also mention about the `metal` installation for risc zero in MacOS

2024-10-28 19:17 UTC, MauroToscano requested changes
It's approved, but don't merge until operators upgrade

2024-10-28 20:32 UTC, JuArce approved these changes
Cases tested in stage:

Operator version: v0.10.2

1. Send old proofs with the old batcher: It is the previous version, and it works. The operator logs that it is using old version of the prover ✅
2. Send new proofs with the old batcher: The batcher rejects the proofs ✅
3. Send new proofs with the new batcher. The operator uses the new version of the provers ✅

2024-11-04 16:00 UTC, MarcosNicolau approved these changes
Worked as expected on Linux and macos!

2024-11-04 21:26 UTC, Oppen commented
> It's approved, but don't merge until operators upgrade

Updates on this?

2024-11-06 21:39 UTC, uri-99 commented
Still waiting , aprox 24hs and we eject unupgraded operators.

2024-11-08 21:24 UTC, MauroToscano approved these changes

2024-11-08 21:24 UTC, merged