feat: Telemetry for the batcher and improve current tracing
yetanotherco/aligned_layer pull request #1335
Opened 2024-10-25 20:32 UTC by IAvecilla

# Telemetry integration for the Batcher

## Description

This PR includes the telemetry integration on the batcher side to log the start of a task and some extra steps between adding more visibility on the different parts that process a given batch.
Now we include what are called `subspans` that are intermediate logs that will pop up instantly on the Jaeger dashboard, now we are able to track on which part of the process a task failed or get lost.

## Type of change

- [x] New feature

## Checklist

- [x] “Hotfix” to `testnet`, everything else to `staging`
- [x] Linked to Github Issue
- [ ] This change depends on code or research by an external entity
  - [ ] Acknowledgements were updated to give credit
- [ ] Unit tests added
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.
- [ ] This change is an Optimization
  - [ ] Benchmarks added/run
- [ ] Has a known issue
  - [Link to the open issue addressing it]() 
- [ ] If your PR changes the Operator compatibility (Ex: Upgrade prover versions)
  - [ ] This PR adds compatibility for operator for both versions and do not change batcher/docs/examples
  - [ ] This PR updates batcher and docs/examples to the newer version. This requires the operator are already updated to be compatible

2024-10-25 22:26 UTC, MarcosNicolau approved these changes
Code looks very good. Tested all traces on my machine ad everything worked as expected.

2024-10-28 19:37 UTC, MauroToscano commented on telemetry_api/lib/telemetry_api/traces.ex
> +        Tracer.add_event("New task taken", [])
```suggestion
        Tracer.add_event("New task received", [])
```

2024-10-28 21:15 UTC, JuArce reviewed
Would be nice a How to test section and a section with which entities requires a new deploy so is easier to prepare the release

2024-10-28 22:28 UTC, JuArce requested changes
Since this PR includes tracing improvements, I would add the following improvements
- Add an event in the aggregator span when the task finally failed or is expired
- Add a event of the Ethereum transaction in the aggregator txs
-

2024-10-28 22:28 UTC, JuArce commented on batcher/aligned-batcher/src/lib.rs
> +            "http://{}",
Protocol is not necessary

2024-10-29 15:44 UTC, IAvecilla commented on batcher/aligned-batcher/src/lib.rs
> +            "http://{}",
I think it is needed it will use the port specified in the config but the protocol is needed to communicate with the telemetry api

2024-11-01 20:23 UTC, Oppen reviewed
Nit: most of the `if let Err(e) ...` case can be replaced by calls to `.inspect_err()`.

2024-11-04 15:17 UTC, JuArce approved these changes

2024-11-04 17:32 UTC, MauroToscano approved these changes

2024-11-04 18:06 UTC, merged