feat(retries): Use config file for retry parameters
yetanotherco/aligned_layer pull request #1467
Opened 2024-11-21 20:25 UTC by PatStiles

# Use config file for retry parameters

## Description

Use config file for retry parameters

## Type of change

Please delete options that are not relevant.

- [x] New feature

2024-11-21 22:45 UTC, uri-99 requested changes

2024-11-21 22:45 UTC, uri-99 commented on core/chainio/avs_writer.go
> +	respondToTaskV2Config.NumRetries = respondToTaskV2NumRetries
should be chain because its a send

2024-11-21 22:45 UTC, uri-99 commented on core/chainio/avs_writer.go
> +	waitForTxConfig.MaxInterval = waitForTxMaxInterval
not sure if network or chain

2024-11-21 22:45 UTC, uri-99 commented on core/chainio/avs_writer.go
> +	simTx, err := w.RespondToTaskV2Retryable(&txOpts, batchMerkleRoot, senderAddress, nonSignerStakesAndSignature, retry.SendToChainRetryParams())
la pregunta del millón

2024-11-21 22:45 UTC, uri-99 commented on core/chainio/avs_writer.go
> +			batchState, _ := w.BatchesStateRetryable(&bind.CallOpts{}, batchIdentifierHash, retry.SendToChainRetryParams())
i think this is network

2024-11-21 22:45 UTC, uri-99 commented on core/retry_test.go
> +	_, err = utils.WaitForTransactionReceiptRetryable(*client, *client, hash, retry.NetworkRetryParams())
chain

2024-11-21 22:45 UTC, uri-99 commented on core/retry_test.go
> +	_, err = utils.WaitForTransactionReceiptRetryable(*client, *client, hash, retry.NetworkRetryParams())
chain

2024-11-21 22:45 UTC, uri-99 commented on core/retry_test.go
> +	_, err = utils.WaitForTransactionReceiptRetryable(*client, *client, hash, retry.NetworkRetryParams())
chain

2024-11-21 22:45 UTC, uri-99 commented on core/retry_test.go
> +	_, err = w.RespondToTaskV2Retryable(&txOpts, zero_bytes, aggregator_address, nonSignerStakesAndSignature, retry.NetworkRetryParams())
chain

2024-11-21 22:45 UTC, uri-99 commented on core/retry_test.go
> +	_, err = w.RespondToTaskV2Retryable(&txOpts, zero_bytes, aggregator_address, nonSignerStakesAndSignature, retry.NetworkRetryParams())
chain

2024-11-21 22:45 UTC, uri-99 commented on core/retry_test.go
> +	_, err = w.RespondToTaskV2Retryable(&txOpts, zero_bytes, aggregator_address, nonSignerStakesAndSignature, retry.NetworkRetryParams())
chain

2024-11-21 23:14 UTC, JuArce commented on core/chainio/avs_writer.go
> +	simTx, err := w.RespondToTaskV2Retryable(&txOpts, batchMerkleRoot, senderAddress, nonSignerStakesAndSignature, retry.SendToChainRetryParams())
Yes

2024-11-21 23:18 UTC, JuArce commented on core/retry_test.go
> +	_, err = utils.WaitForTransactionReceiptRetryable(*client, *client, hash, retry.NetworkRetryParams())
agree

2024-11-21 23:18 UTC, JuArce commented on core/retry_test.go
> +	_, err = utils.WaitForTransactionReceiptRetryable(*client, *client, hash, retry.NetworkRetryParams())
agree

2024-11-21 23:18 UTC, JuArce commented on core/retry_test.go
> +	_, err = utils.WaitForTransactionReceiptRetryable(*client, *client, hash, retry.NetworkRetryParams())
agree

2024-11-21 23:19 UTC, JuArce commented on core/retry_test.go
> +	_, err = w.RespondToTaskV2Retryable(&txOpts, zero_bytes, aggregator_address, nonSignerStakesAndSignature, retry.NetworkRetryParams())
agree

2024-11-21 23:25 UTC, uri-99 approved these changes

2024-11-21 23:28 UTC, uri-99 approved these changes

2024-11-21 23:29 UTC, MauroToscano approved these changes

2024-11-22 14:49 UTC, JuArce approved these changes

2024-11-22 15:11 UTC, merged