1527 feat make targets to modify strategies
yetanotherco/aligned_layer pull request #1530
Opened 2024-11-29 17:17 UTC by uri-99

# Make targets to read and modify strategy weights

## Description

This functionality is needed since strategy weights change over time

## Type of change

- [x] New feature
- [ ] Bug fix
- [ ] Optimization
- [ ] Refactor

## Checklist

- [ ] “Hotfix” to `testnet`, everything else to `staging`
- [ ] Linked to Github Issue
- [ ] This change depends on code or research by an external entity
  - [ ] Acknowledgements were updated to give credit
- [ ] Unit tests added
- [x] This change requires new documentation.
  - [ ] Documentation has been added/updated.
- [ ] This change is an Optimization
  - [ ] Benchmarks added/run
- [ ] Has a known issue
  - [Link to the open issue addressing it]() 
- [ ] If your PR changes the Operator compatibility (Ex: Upgrade prover versions)
  - [ ] This PR adds compatibility for operator for both versions and do not change batcher/docs/examples
  - [ ] This PR updates batcher and docs/examples to the newer version. This requires the operator are already updated to be compatible

2024-11-29 20:46 UTC, avilagaston9 commented on docs/0_internal/6_a_modify_strategies.md
> +This doc contains a guide on how to use the modify the strategy weight multipliers on Aligned.
```suggestion
This doc contains a guide on how to modify the strategy weight multipliers on Aligned.
```

2024-11-29 20:53 UTC, PatStiles commented on docs/0_internal/6_a_modify_strategies.md
> +This doc contains a guide on how to use the modify the strategy weight multipliers on Aligned.
addressed!

2024-11-29 21:03 UTC, avilagaston9 approved these changes
LGTM!

2024-12-05 13:00 UTC, PatStiles approved these changes

2024-12-10 15:01 UTC, JuArce requested changes

2024-12-10 15:01 UTC, JuArce commented on docs/0_internal/6_b_1_propose_modify_strategies.md
> +TODO pic
Complete the TODO

2024-12-10 15:01 UTC, JuArce commented on Makefile
> +	@. contracts/scripts/.env && . contracts/scripts/update_strategy_weight.sh $(STRATEGY_INDICES) $(NEW_MULTIPLIERS)
Missing the $NETWORK

2025-01-09 14:46 UTC, JuArce approved these changes

2025-01-09 15:31 UTC, merged