fix(batcher): User Balance check does not work for replacement messages.
yetanotherco/aligned_layer pull request #1559
Opened 2024-12-03 15:54 UTC by PatStiles

# User Balance check does not work for replacement messages

## Description

Currently the user balance is checked to ensure a user can pay for all there submitted proofs. Currently this check is done before replacement messages are handled and does not compute the total balance of proofs with replacement msg in mind. This leads to issues that when a replacement msg is posted the user balance check will fail as the batcher will check the total accumulated proof including the current msg to be replaced + the fee of the replacement msg. The check will fail as the contribution of the msg being replaced will be counted twice (first in the accumulated balance, and as the next proof added to the batch. 

This pr addresses this issue by the following:
- Relocates the user balance check logic to be after the replacement_msg_check
- Creates a separate balance check for replacement msgs that subtracts the `original_msg_max_fee` from the user_balance

## Type of change

Please delete options that are not relevant.

- [x] Bug fix

## Checklist

- [ ] “Hotfix” to `testnet`, everything else to `staging`
- [ ] Linked to Github Issue
- [ ] This change depends on code or research by an external entity
  - [ ] Acknowledgements were updated to give credit
- [ ] Unit tests added
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.
- [ ] This change is an Optimization
  - [ ] Benchmarks added/run
- [ ] Has a known issue
  - [Link to the open issue addressing it]() 
- [ ] If your PR changes the Operator compatibility (Ex: Upgrade prover versions)
  - [ ] This PR adds compatibility for operator for both versions and do not change batcher/docs/examples
  - [ ] This PR updates batcher and docs/examples to the newer version. This requires the operator are already updated to be compatible

2024-12-04 15:58 UTC, MarcosNicolau approved these changes
Works nice!

2024-12-05 19:24 UTC, uri-99 requested changes

2024-12-05 19:24 UTC, uri-99 commented on batcher/aligned-batcher/src/lib.rs
> +        msg_max_fee: U256,
this parameter is already in `nonced_verification_data`

2024-12-05 19:24 UTC, uri-99 commented on batcher/aligned-batcher/src/lib.rs
> +        user_accumulated_fee: U256,
i would rename to `current_`

2024-12-05 19:24 UTC, uri-99 commented on batcher/aligned-batcher/src/lib.rs
> +            msg_max_fee,
use `replacement_max_fee`

2024-12-05 20:44 UTC, uri-99 approved these changes

2024-12-05 21:26 UTC, avilagaston9 approved these changes
Works in my machine!

2025-08-21 19:56 UTC, MauroToscano commented
This is stale

2025-08-21 19:56 UTC, closed without merging