feat(sdk): SDK changes
yetanotherco/aligned_layer pull request #1568
Opened 2024-12-04 14:41 UTC by PatStiles

# SDK Changes

## Description

Makes some changes to sdk:
- Derives `batcher_url` from Network paramater.
- Adds `--private_key` flag to DepositToBatcher
- Adds msg to batcher errors telling a user there funds have not been spent.

## Type of change

Please delete options that are not relevant.

- [x] New feature
- [ ] Bug fix
- [ ] Optimization
- [ ] Refactor

## Checklist

- [ ] “Hotfix” to `testnet`, everything else to `staging`
- [ ] Linked to Github Issue
- [ ] This change depends on code or research by an external entity
  - [ ] Acknowledgements were updated to give credit
- [ ] Unit tests added
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.
- [ ] This change is an Optimization
  - [ ] Benchmarks added/run
- [ ] Has a known issue
  - [Link to the open issue addressing it]() 
- [ ] If your PR changes the Operator compatibility (Ex: Upgrade prover versions)
  - [ ] This PR adds compatibility for operator for both versions and do not change batcher/docs/examples
  - [ ] This PR updates batcher and docs/examples to the newer version. This requires the operator are already updated to be compatible

2024-12-04 15:08 UTC, uri-99 commented on batcher/aligned/src/main.rs
> +    batcher_url: Option<String>,
this should no longer be an option. with --network is enough.

2024-12-04 15:09 UTC, uri-99 commented on batcher/aligned/src/main.rs
> +    private_key: Option<String>,
if this is an option, keystore should not be `required=true`.
also we should only accept 1 of these 2 options

2024-12-04 15:09 UTC, uri-99 commented on batcher/aligned/src/main.rs
>      )]
remove

2024-12-04 15:10 UTC, uri-99 commented on batcher/aligned/src/main.rs
> +                .batcher_url
no, get url from network argument

2024-12-04 15:10 UTC, MarcosNicolau commented on batcher/aligned/src/main.rs
> +    batcher_url: Option<String>,
But what if somebody has its own batcher?

2024-12-04 15:11 UTC, uri-99 commented on batcher/aligned/src/main.rs
>                  warn!("Missing keystore used for payment.");
the missing info is not necesarrily a keystore, it can be private key. so text should be like "missing keystore or private key used for payment"

2024-12-04 15:12 UTC, uri-99 commented on batcher/aligned/src/main.rs
> +            let private_key = &deposit_to_batcher_args.private_key;
add here only 1 of these can be set, to avoid user setting conflicting private key AND keystore.

2024-12-04 15:12 UTC, uri-99 commented on batcher/aligned/src/main.rs
> +            let batcher_url = args.batcher_url.unwrap_or(network.get_batcher_url().into());
no, get batcher url from network arg

2024-12-04 15:13 UTC, uri-99 requested changes
left some comments

2024-12-04 20:39 UTC, MarcosNicolau commented
@uri-99, your comments have been addressed at: [2e8465c](https://github.com/yetanotherco/aligned_layer/pull/1568/commits/2e8465ca4791c7022d4356fe8f61f97bd7ee43d3).

2024-12-05 20:52 UTC, uri-99 requested changes
missing remove batcher-url from rust task sender.

2024-12-05 22:57 UTC, uri-99 approved these changes

2024-12-18 23:20 UTC, Oppen approved these changes

2025-01-02 21:02 UTC, JulianVentura approved these changes
Works as expected!
There are some docs conflicts

2025-01-06 17:52 UTC, avilagaston9 commented on batcher/aligned/src/main.rs
> +                }
We could have used a group for this: https://stackoverflow.com/questions/76315540/how-do-i-require-one-of-the-two-clap-options

2025-01-06 21:08 UTC, MauroToscano requested changes
This PR should be splitted in different PRs. Also, default network params is fine, but we should have a way to change the batcher url manually, let's re review this over the following days

2025-01-08 20:24 UTC, closed without merging