Add SSL termination to the explorer
yetanotherco/aligned_layer pull request #1586
Opened 2024-12-06 13:34 UTC by klaus993

# Add SSL termination to the explorer

## Description

Manage SSL termination directly from the explorer, to remove the reverse-proxy dependency (caddy)

## Changes

* `explorer/lib/explorer_web/router.ex`: make CSP less strict for the website to be able to:
  * `'unsafe-inline'`: execute JS scripts inline
  * `img-src https://w3.org blob: data:;`: fetch some image/data from w3
* `explorer/config/runtime.exs`: handle SSL certificates from elixir endpoint
  * `PORT_SSL` env var sets the port for HTTPS endpoint to listen on, not needed as it's defaulted to 443
  * `KEYFILE_PATH` and `CERTFILE_PATH` are the local paths to the SSL private key and the certificate, if not set, HTTP endpoint will be brought up, but not HTTPS one
  * NOTE: as this config is all inside the `if config_env() == :prod`, local development setup changes are not needed

2024-12-10 17:06 UTC, JuArce requested changes
There is missing the grafana dashboard changes

2024-12-10 18:19 UTC, PatStiles approved these changes

2024-12-16 14:05 UTC, JuArce approved these changes

2024-12-16 15:10 UTC, samoht9277 approved these changes
Works as intended

2024-12-16 16:08 UTC, merged