fear(docs):  Add aligned-cli readme
yetanotherco/aligned_layer pull request #1590
Opened 2024-12-06 21:01 UTC by PatStiles

# Aligned CLI readme

## Description

Adds an readme for the aligned CLI that displays and describes all its flags and parameters. This is intended to be used in alongside the other examples within the documentation for usage.

A separate PR should be done to make the naming conventions throughout the repo consistent. ref: https://github.com/yetanotherco/aligned_layer/issues/1589 . It would be recommended to do this in parts as it may introduce breaking changes.

## Type of change

Please delete options that are not relevant.

- [x] New feature

## Checklist

- [ ] “Hotfix” to `testnet`, everything else to `staging`
- [ ] Linked to Github Issue
- [ ] This change depends on code or research by an external entity
  - [ ] Acknowledgements were updated to give credit
- [ ] Unit tests added
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.
- [ ] This change is an Optimization
  - [ ] Benchmarks added/run
- [ ] Has a known issue
  - [Link to the open issue addressing it]() 
- [ ] If your PR changes the Operator compatibility (Ex: Upgrade prover versions)
  - [ ] This PR adds compatibility for operator for both versions and do not change batcher/docs/examples
  - [ ] This PR updates batcher and docs/examples to the newer version. This requires the operator are already updated to be compatible

2024-12-09 21:47 UTC, MarcosNicolau commented on docs/3_guides/9_aligned_cli.md
> +```
```suggestion
2. A source command will be printed in your terminal after installation. Execute that command to update your shell environment.
3. Verify that the installation went fine:
```bash
aligned --help
```
```

2024-12-09 21:47 UTC, MarcosNicolau commented on docs/3_guides/9_aligned_cli.md
> +    - Args:
```suggestion
    - Options:
```

2024-12-09 21:47 UTC, MarcosNicolau commented on docs/3_guides/9_aligned_cli.md
> +    - Args:
```suggestion
    - Options:
```

2024-12-09 21:47 UTC, MarcosNicolau commented on docs/3_guides/9_aligned_cli.md
> +    - Args:
```suggestion
    - Options:
```

2024-12-09 21:47 UTC, MarcosNicolau commented on docs/3_guides/9_aligned_cli.md
> +    - Args:
```suggestion
    - Options:
```

2024-12-09 21:47 UTC, MarcosNicolau commented on docs/3_guides/9_aligned_cli.md
> +    - Args:
```suggestion
    - Options:
```

2024-12-09 21:47 UTC, MarcosNicolau commented on docs/3_guides/9_aligned_cli.md
> +    - Args:
```suggestion
    - Options:
```

2024-12-09 21:47 UTC, MarcosNicolau commented on docs/3_guides/9_aligned_cli.md
> +## Commands:
I would also add `--help` usage, for example:

## Help

To see the available commands run:
```bash
aligned --help 
```

To see the usage of a command run:
```bash
aligned [COMMAND] --help
```

2024-12-09 21:47 UTC, MarcosNicolau commented on docs/3_guides/9_aligned_cli.md
> +An workflow example workflow for using the Aligned CLI on Holesky would be the following:
```suggestion
Here is a workflow example when using the Aligned CLI:
```

2024-12-09 21:47 UTC, MarcosNicolau commented on docs/3_guides/9_aligned_cli.md
> +aligned submit  --proving_system Risc0 --proof ../../scripts/test_files/risc_zero/fibonacci_proof_generator/risc_zero_fibonacci.proof --vm_program ../../scripts/test_files/risc_zero/fibonacci_proof_g
```suggestion
aligned submit  --proving_system Risc0 --proof risc_zero_fibonacci.proof --vm_program  fibonacci_id.bin --public_input risc_zero_fibonacci.pub --repetitions <BURST_SIZE> --keystore_path <YOUR_KEYSTORE_PATH> --network holesky --max_fee 1300000000
```

2024-12-10 14:56 UTC, PatStiles commented on docs/3_guides/9_aligned_cli.md
> +aligned submit  --proving_system Risc0 --proof ../../scripts/test_files/risc_zero/fibonacci_proof_generator/risc_zero_fibonacci.proof --vm_program ../../scripts/test_files/risc_zero/fibonacci_proof_g
addressed! Changes to work from root of github repo.

2024-12-10 15:02 UTC, MarcosNicolau reviewed
Looks good! We should wait until the other CLI prs get merged before merging one.

2024-12-10 17:10 UTC, JuArce requested changes
There is missing to update the summary.MD

2024-12-10 17:28 UTC, PatStiles commented
> There is missing to update the summary.MD

Cambio! @JuArce I also added a missing link for `Submitting Batch without Batcher`

2024-12-23 18:17 UTC, JuArce requested changes

2024-12-23 18:17 UTC, JuArce commented on docs/3_guides/9_aligned_cli.md
> +        - `--batcher_url <Batcher connection address>`: Websocket URL for the Aligned Layer batcher.
Add the common urls: holesky and mainnet

2024-12-23 18:17 UTC, JuArce commented on docs/3_guides/9_aligned_cli.md
> +        - `--max_fee <Max Fee (ether)>`: Amount of Ethereum in Wei to deposit into the `BatcherPaymentService.sol` contract to pay for proof submission.
Add an example

2024-12-23 18:17 UTC, JuArce commented on docs/3_guides/9_aligned_cli.md
> +        - `--amount <Amount to deposit>`: Amount of Ethereum in Wei to deposit into the `BatcherPaymentService.sol` contract to pay for proof submission.
add an example

2024-12-23 18:17 UTC, JuArce commented on docs/3_guides/9_aligned_cli.md
> +        - `--batcher_url <Batcher connection address>`: Websocket URL for the Aligned Layer batcher.
Add possible values

2024-12-23 18:17 UTC, JuArce commented on docs/3_guides/9_aligned_cli.md
> +aligned deposit-to-batcher --network holesky --amount 0.5ether --keystore_path <KEYSTORE_PATH>
deposit to batcher spec is in wei and it is using ether. Check which one is correct

2024-12-23 18:17 UTC, JuArce commented on docs/3_guides/9_aligned_cli.md
> +aligned get-user-balance --user_addr <WALLET_ADDRESS> --network holesky
It says holesky, but does not specify the batcher_url

2024-12-23 18:17 UTC, JuArce commented on docs/3_guides/9_aligned_cli.md
> +aligned submit  --proving_system Risc0 --proof ./scripts/test_files/risc_zero/fibonacci_proof_generator/risc_zero_fibonacci.proof --vm_program ./scripts/test_files/risc_zero/fibonacci_proof_generator
missing batcher_url

2025-01-02 19:58 UTC, PatStiles commented on docs/3_guides/9_aligned_cli.md
> +        - `--batcher_url <Batcher connection address>`: Websocket URL for the Aligned Layer batcher.
addressed!

2025-01-02 19:58 UTC, PatStiles commented on docs/3_guides/9_aligned_cli.md
> +        - `--batcher_url <Batcher connection address>`: Websocket URL for the Aligned Layer batcher.
addressed!

2025-01-02 20:06 UTC, PatStiles commented on docs/3_guides/9_aligned_cli.md
> +        - `--max_fee <Max Fee (ether)>`: Amount of Ethereum in Wei to deposit into the `BatcherPaymentService.sol` contract to pay for proof submission.
Example usage for `submit` is added in the section below this. Did you want me to make one in line here?

2025-01-02 20:06 UTC, PatStiles commented on docs/3_guides/9_aligned_cli.md
> +        - `--amount <Amount to deposit>`: Amount of Ethereum in Wei to deposit into the `BatcherPaymentService.sol` contract to pay for proof submission.
Example usage for `deposit-to-batcher` is added in the section below this. Did you want me to make one in line here?

2025-01-02 20:07 UTC, PatStiles commented on docs/3_guides/9_aligned_cli.md
> +aligned deposit-to-batcher --network holesky --amount 0.5ether --keystore_path <KEYSTORE_PATH>
Fixed!

2025-01-02 20:07 UTC, PatStiles commented on docs/3_guides/9_aligned_cli.md
> +aligned get-user-balance --user_addr <WALLET_ADDRESS> --network holesky
Fixed!

2025-01-02 20:07 UTC, PatStiles commented on docs/3_guides/9_aligned_cli.md
> +aligned submit  --proving_system Risc0 --proof ./scripts/test_files/risc_zero/fibonacci_proof_generator/risc_zero_fibonacci.proof --vm_program ./scripts/test_files/risc_zero/fibonacci_proof_generator
addressed!

2025-01-06 20:21 UTC, uri-99 approved these changes

2025-01-06 20:40 UTC, uri-99 approved these changes

2025-01-07 14:41 UTC, uri-99 approved these changes

2025-01-07 20:32 UTC, JuArce approved these changes

2025-01-08 15:08 UTC, avilagaston9 approved these changes
LGTM

2025-01-08 15:08 UTC, avilagaston9 commented on docs/3_guides/9_aligned_cli.md
> +  - Holesky: `https://ethereum-holesky-rpc.publicnode.com`
Nit: I think it should say either Testnet or Holesky.

2025-01-08 18:27 UTC, JuArce commented on docs/3_guides/9_aligned_cli.md
> +  - Holesky: `https://ethereum-holesky-rpc.publicnode.com`
Done

2025-01-08 20:10 UTC, merged