feat: aggregator total gas paid metric
yetanotherco/aligned_layer pull request #1592
Opened 2024-12-06 21:58 UTC by JulianVentura

# Aggregator total gas paid metric

## Description

This PR adds aggregator total gas paid while responding to tasks metric to the grafana dashboard.

## How to test

1. Start all services locally, including the metrics
2. Start sending proofs
3. Go to the "System Data" dashboard, you should see a new panel showing the total amount of ETH paid by the aggregator, right down the gas price of the last batch.
4. Shut down the aggregator and start it over again
5. You should see that on new batch finished, the metric will keep accumulating on previous data.

## Type of change

Please delete options that are not relevant.

- [X] New feature
- [ ] Bug fix
- [ ] Optimization
- [ ] Refactor

## Checklist

- [ ] “Hotfix” to `testnet`, everything else to `staging`
- [ ] Linked to Github Issue
- [ ] This change depends on code or research by an external entity
  - [ ] Acknowledgements were updated to give credit
- [ ] Unit tests added
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.
- [ ] This change is an Optimization
  - [ ] Benchmarks added/run
- [ ] Has a known issue
  - [Link to the open issue addressing it]() 
- [ ] If your PR changes the Operator compatibility (Ex: Upgrade prover versions)
  - [ ] This PR adds compatibility for operator for both versions and do not change batcher/docs/examples
  - [ ] This PR updates batcher and docs/examples to the newer version. This requires the operator are already updated to be compatible

2024-12-07 00:06 UTC, PatStiles commented
Ran it locally and it observed the expected behavior

2024-12-07 00:07 UTC, PatStiles approved these changes

2024-12-07 00:07 UTC, PatStiles commented on core/chainio/avs_writer.go
> +// Calculates the transaction cost from the receipt and updates the total amount paid by the aggregaot metric
small nit: `aggregaot` -> `aggregator`

2024-12-09 21:22 UTC, MarcosNicolau commented on grafana/provisioning/dashboards/aligned/aggregator_batcher.json
> +      "description": "Accumulated gas cost the aggregator paid for the batcher when the tx cost was higher than the respondToTaskFeeLimit.",
```suggestion
      "description": "Accumulated gas cost in ETH the Aggregator paid in when sending RespondToTask transactions.",
```

2024-12-09 21:29 UTC, MarcosNicolau approved these changes
Works as expected.

2024-12-10 19:46 UTC, uri-99 requested changes

2024-12-10 19:46 UTC, uri-99 commented on metrics/metrics.go
> +	aggregatorGasCostPaidTotal             prometheus.Gauge
this should be a counter

2024-12-10 19:46 UTC, uri-99 commented on metrics/metrics.go
> +	m.aggregatorGasCostPaidTotal.Add(value)
yes, a counter.
gauges get "current data" , they can go up or down, like a pressure gauge of a steam machine.
a counter is for increments like this one, of values that count x occurrances, like km travelled with a car

2024-12-10 19:55 UTC, uri-99 requested changes
Edit: removed comment

2024-12-10 20:15 UTC, JulianVentura commented on metrics/metrics.go
> +	m.aggregatorGasCostPaidTotal.Add(value)
Yep, seems that's right. I'll do the change

2024-12-10 21:09 UTC, uri-99 approved these changes

2024-12-10 21:21 UTC, JuArce approved these changes

2024-12-10 21:29 UTC, merged