hotfix: telemetry script to rewrite operator names
yetanotherco/aligned_layer pull request #1600
Opened 2024-12-10 14:58 UTC by uri-99

# TITLE

## Description

Description of the pull request changes and motivation.

## Type of change

Please delete options that are not relevant.

- [ ] New feature
- [ ] Bug fix
- [ ] Optimization
- [ ] Refactor

## Checklist

- [ ] “Hotfix” to `testnet`, everything else to `staging`
- [ ] Linked to Github Issue
- [ ] This change depends on code or research by an external entity
  - [ ] Acknowledgements were updated to give credit
- [ ] Unit tests added
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.
- [ ] This change is an Optimization
  - [ ] Benchmarks added/run
- [ ] Has a known issue
  - [Link to the open issue addressing it]() 
- [ ] If your PR changes the Operator compatibility (Ex: Upgrade prover versions)
  - [ ] This PR adds compatibility for operator for both versions and do not change batcher/docs/examples
  - [ ] This PR updates batcher and docs/examples to the newer version. This requires the operator are already updated to be compatible

2024-12-10 17:30 UTC, PatStiles approved these changes

2025-01-15 15:40 UTC, JuArce requested changes
There is missing instructions on how to use

2025-01-15 18:15 UTC, Oppen commented on telemetry_api/scripts/fetch_operators_metadata.sh
> +iex --sname fetch_operators_metadata --remsh telemetry@$ELIXIR_HOSTNAME
Maybe we could just echo the command?

```sh
echo "Scripts.FetchOperatorsMetadata.run()" | iex --sname fetch_operators_metadata --remsh telemetry@$ELIXIR_HOSTNAME
```

Am I missing something that makes that not work?

2025-01-15 18:36 UTC, Oppen approved these changes
LGTM

2025-01-20 18:14 UTC, MauroToscano commented
No longer needed

2025-01-20 18:14 UTC, closed without merging