feat(explorer): selector for the network
yetanotherco/aligned_layer pull request #1622
Opened 2024-12-16 18:14 UTC by MarcosNicolau

# TITLE

## Description

Description of the pull request changes and motivation.

## Type of change

Please delete options that are not relevant.

- [ ] New feature
- [ ] Bug fix
- [ ] Optimization
- [ ] Refactor

## Checklist

- [ ] “Hotfix” to `testnet`, everything else to `staging`
- [ ] Linked to Github Issue
- [ ] This change depends on code or research by an external entity
  - [ ] Acknowledgements were updated to give credit
- [ ] Unit tests added
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.
- [ ] This change is an Optimization
  - [ ] Benchmarks added/run
- [ ] Has a known issue
  - [Link to the open issue addressing it]() 
- [ ] If your PR changes the Operator compatibility (Ex: Upgrade prover versions)
  - [ ] This PR adds compatibility for operator for both versions and do not change batcher/docs/examples
  - [ ] This PR updates batcher and docs/examples to the newer version. This requires the operator are already updated to be compatible

2024-12-16 18:34 UTC, uri-99 commented on explorer/lib/explorer_web/live/utils.ex
> +      {"Holesky", "https://holesky.explorer.alignedlayer.com"}
missing staging

2024-12-16 18:43 UTC, uri-99 approved these changes

2024-12-16 19:59 UTC, uri-99 requested changes
we should go to staging

2024-12-16 20:05 UTC, uri-99 commented
The many file changes should go away when #1625  is merged

2024-12-17 16:05 UTC, uri-99 approved these changes

2024-12-17 21:29 UTC, PatStiles approved these changes

2024-12-18 20:58 UTC, Oppen approved these changes
It works on my machine. It's a little odd that because it works by redirecting to the other domains the UI itself changes. I would have expected as user that only the data it showed would change.

2024-12-18 21:01 UTC, MarcosNicolau commented
> It works on my machine. It's a little odd that because it works by redirecting to the other domains the UI itself changes. I would have expected as user that only the data it showed would change.

It also seemed odd to me at first, but if you check sites like [etherscan](https://etherscan.io/) they do the same.

2024-12-19 15:40 UTC, merged