feat(explorer): mark pending batches in red after 5 minutes
yetanotherco/aligned_layer pull request #1624
Opened 2024-12-16 19:12 UTC by Oppen

# TITLE

## Description

Description of the pull request changes and motivation.

## Type of change

Please delete options that are not relevant.

- [ ] New feature
- [ ] Bug fix
- [ ] Optimization
- [ ] Refactor

## Checklist

- [ ] “Hotfix” to `testnet`, everything else to `staging`
- [ ] Linked to Github Issue
- [ ] This change depends on code or research by an external entity
  - [ ] Acknowledgements were updated to give credit
- [ ] Unit tests added
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.
- [ ] This change is an Optimization
  - [ ] Benchmarks added/run
- [ ] Has a known issue
  - [Link to the open issue addressing it]() 
- [ ] If your PR changes the Operator compatibility (Ex: Upgrade prover versions)
  - [ ] This PR adds compatibility for operator for both versions and do not change batcher/docs/examples
  - [ ] This PR updates batcher and docs/examples to the newer version. This requires the operator are already updated to be compatible

2024-12-16 19:59 UTC, uri-99 approved these changes

2024-12-17 11:51 UTC, MarcosNicolau approved these changes
Nice, I updated your comment with a testing section :+1:

2024-12-17 23:47 UTC, PatStiles approved these changes

2024-12-18 04:15 UTC, Oppen commented
> Nice, I updated your comment with a testing section 👍

Thanks! Forgot about it, just promoted the draft. I'll update myself tomorrow for the other one.

2024-12-18 04:18 UTC, Oppen commented on explorer/lib/explorer_web/live/utils.ex
> +    Time.after?(Time.utc_now(), expiration)
This could also be done like this:
```suggestion
    Time.add(batch.submission_timestamp, 5, :minute)
    |> Time.before?(Time.utc_now())
```

2024-12-18 04:19 UTC, Oppen commented on explorer/lib/explorer_web/live/utils.ex
> +    Time.after?(Time.utc_now(), expiration)
But, also, I think I should be using `DateTime`, will fix in the morning. `Time.add` discards the date so this would break overnight.

2024-12-18 18:55 UTC, uri-99 reviewed
.

2024-12-18 18:55 UTC, uri-99 requested changes
.

2024-12-18 19:53 UTC, uri-99 approved these changes

2024-12-19 15:37 UTC, merged