feat(explorer): Add Restaking tab to nav bar
yetanotherco/aligned_layer pull request #1640
Opened 2024-12-18 08:30 UTC by PatStiles

# Add Restaking tab to nav bar

## Description

Adds a restaking tab to the explorer navigation bar that links to the restaking page.

## Testing

Start a local devnet.
Run the explorer.
Ensure clicking on `Restaking` links to the correct page.

## Type of change

Please delete options that are not relevant.

- [x] New feature

## Checklist

- [ ] “Hotfix” to `testnet`, everything else to `staging`
- [ ] Linked to Github Issue
- [ ] This change depends on code or research by an external entity
  - [ ] Acknowledgements were updated to give credit
- [ ] Unit tests added
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.
- [ ] This change is an Optimization
  - [ ] Benchmarks added/run
- [ ] Has a known issue
  - [Link to the open issue addressing it]() 
- [ ] If your PR changes the Operator compatibility (Ex: Upgrade prover versions)
  - [ ] This PR adds compatibility for operator for both versions and do not change batcher/docs/examples
  - [ ] This PR updates batcher and docs/examples to the newer version. This requires the operator are already updated to be compatible

2024-12-18 15:31 UTC, MarcosNicolau reviewed
Careful, on smaller devices the page goes out of bounds. Also, you need to add to the mobile nav menu.

2024-12-18 16:20 UTC, uri-99 requested changes

2024-12-18 16:20 UTC, uri-99 commented on explorer/lib/explorer_web/components/nav.ex
> +            Restaking
```suggestion
            Assets
```

2024-12-18 16:30 UTC, uri-99 approved these changes

2024-12-18 20:01 UTC, Oppen approved these changes
Works but the button name is `Assets`, not `Restaking`.

2024-12-19 15:48 UTC, MarcosNicolau approved these changes

2024-12-19 16:20 UTC, merged