feat(explorer): Fix nav bar
yetanotherco/aligned_layer pull request #1660
Opened 2024-12-19 16:42 UTC by PatStiles

# Fix explorer nav bar

## Description

Previously the nav bar had inconsistent behavior when resizing. Some elements were at different breakpoints and the search bar was not auto resizing leading to elements being cut off the screen.

## Type of change

Please delete options that are not relevant.

- [ ] New feature
- [x] Bug fix
- [ ] Optimization
- [ ] Refactor

## Checklist

- [ ] “Hotfix” to `testnet`, everything else to `staging`
- [ ] Linked to Github Issue
- [ ] This change depends on code or research by an external entity
  - [ ] Acknowledgements were updated to give credit
- [ ] Unit tests added
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.
- [ ] This change is an Optimization
  - [ ] Benchmarks added/run
- [ ] Has a known issue
  - [Link to the open issue addressing it]() 
- [ ] If your PR changes the Operator compatibility (Ex: Upgrade prover versions)
  - [ ] This PR adds compatibility for operator for both versions and do not change batcher/docs/examples
  - [ ] This PR updates batcher and docs/examples to the newer version. This requires the operator are already updated to be compatible

2024-12-19 16:47 UTC, uri-99 requested changes

2024-12-19 16:47 UTC, uri-99 commented on explorer/lib/explorer_web/components/nav.ex
add more space between these 2: (docs and search bar)
<img width="128" alt="image" src="https://github.com/user-attachments/assets/4f53fadc-fd94-4329-b739-f136fe875180" />

2024-12-19 16:47 UTC, uri-99 commented on explorer/lib/explorer_web/components/nav.ex
when i shrink the screen there is a point where items dissapear:
<img width="652" alt="image" src="https://github.com/user-attachments/assets/2aa3fa34-f4c2-4ae4-a4c4-4b4998cd2f4b" />

2024-12-19 17:04 UTC, PatStiles commented on explorer/lib/explorer_web/components/nav.ex
addressed!

2024-12-20 17:20 UTC, uri-99 approved these changes

2024-12-20 17:20 UTC, merged