hotfix: make aggregator fee multiplier customizable
yetanotherco/aligned_layer pull request #1690
Opened 2024-12-30 18:57 UTC by Oppen

- **hotfix(batcher): reduce cost constants**
- **hotfix: make aggregator fee multiplier customizable**

# TITLE

## Description

Description of the pull request changes and motivation.

## Type of change

Please delete options that are not relevant.

- [ ] New feature
- [ ] Bug fix
- [ ] Optimization
- [ ] Refactor

## Checklist

- [ ] “Hotfix” to `testnet`, everything else to `staging`
- [ ] Linked to Github Issue
- [ ] This change depends on code or research by an external entity
  - [ ] Acknowledgements were updated to give credit
- [ ] Unit tests added
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.
- [ ] This change is an Optimization
  - [ ] Benchmarks added/run
- [ ] Has a known issue
  - [Link to the open issue addressing it]() 
- [ ] If your PR changes the Operator compatibility (Ex: Upgrade prover versions)
  - [ ] This PR adds compatibility for operator for both versions and do not change batcher/docs/examples
  - [ ] This PR updates batcher and docs/examples to the newer version. This requires the operator are already updated to be compatible

2025-01-02 13:36 UTC, MarcosNicolau approved these changes
Works for me.

2025-01-02 17:55 UTC, PatStiles approved these changes
Worked locally LGTM

2025-01-02 18:39 UTC, uri-99 approved these changes

2025-01-02 18:39 UTC, uri-99 commented on batcher/aligned-sdk/src/core/constants.rs
> +pub const ADDITIONAL_SUBMISSION_GAS_COST_PER_PROOF: u128 = 2_000;
verify this number is OK.

2025-01-02 19:18 UTC, uri-99 commented on batcher/aligned-sdk/src/core/constants.rs
> +pub const ADDITIONAL_SUBMISSION_GAS_COST_PER_PROOF: u128 = 2_000;
yes it is ok

2025-01-08 17:06 UTC, JuArce approved these changes

2025-01-08 19:41 UTC, uri-99 approved these changes

2025-01-08 21:09 UTC, avilagaston9 requested changes
We are debugging an issue when trying to submit only one proof

2025-01-08 22:16 UTC, avilagaston9 approved these changes
We understood the problem. It wasn't an issue!

2025-01-09 14:09 UTC, avilagaston9 commented
I think we should also update `infra/ansible/playbooks/templates/config-files/config-batcher.yaml.j2`.

2025-01-09 17:52 UTC, PatStiles approved these changes

2025-01-09 19:14 UTC, JulianVentura approved these changes

2025-01-10 14:32 UTC, merged