fix(operator): Operator panic's when reconnect fails after max retries
yetanotherco/aligned_layer pull request #1692
Opened 2024-12-30 20:14 UTC by PatStiles

# Fix: Operator Panic when reconnect fails after max Retries

## Description

Closes #960. When `SubscribeToNewTasksV2Retryable` and `SubscribeToNewTasksV3Retryable` exhaust the maximum number of retries the respective subscribe functions panics due to dereferencing a `nil` reference within the generated contract bindings. This pr addressed this issue by:
1.) Adding a `defer()` to the go routine the converts the panic into an error before the operator process exits.
2.) Changing the retry parameters for `SubscribeToNewTasksV2Retryable` and `SubscribeToNewTasksV3Retryable` to retry infinitely (up to retry intervals of 60 sec).

### To Test:
- install and use nginx  as a proxy to test the connection `brew install nginx`
- create a directory nginx with the file nginx.conf inside of it, with this content:
```
events { }

http {
    server {
        listen 8082;

        location /main/ {
            proxy_pass http://host.docker.internal:8545/;  # Note the trailing slashes
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_connect_timeout 1d;
            proxy_send_timeout 1d;
            proxy_read_timeout 1d;
        }
    }
}
```
- create a docker compose with the following contents:
```
version: '3'
services:
  nginx:
    image: nginx:alpine
    container_name: nginx-anvil-proxy
    volumes:
      - ./nginx:/etc/nginx
    ports:
      - "8082:8082"
 ```
 - change the respective url's in `config-files` within the aligned-layer repo to use `:8082/main/` port and path.
 - Start a local anvil node `make anvil_start_with_block_time`
 - Start nginx in a docker container via `docker compose -f nginx-docker-compose.yaml up -d`
 - Observe proof verification is successful.
 - kill the connection to anvil via `docker compose -f nginx-docker-compose.yaml stop`
 - observe operator blocks with the following message:
 
<img width="1048" alt="Screenshot 2024-12-30 at 17 08 42" src="https://github.com/user-attachments/assets/be4627db-0eee-4bf9-a94c-186b8214afd6" />

- Start the nginx proxy again `docker compose -f nginx-docker-compose.yaml up -d` && restart the aggregator `make aggregator_start`
- Observe the operator reconnects and start verifying batches
<img width="1048" alt="Screenshot 2024-12-30 at 17 10 41" src="https://github.com/user-attachments/assets/2df42296-0c87-4942-af36-29c668d30bb8" />
Panic Operation:
- change line 49 in `core/retry.go` to 	
```
SubscribeToNewTasksNumRetries = 1
```
- Start the local network with the nginx proxy as described above and kill the proxy
- Observe the operator errors and shuts down with the panic wrapped within an error.

<img width="1048" alt="Screenshot 2024-12-30 at 16 42 17" src="https://github.com/user-attachments/assets/f8d09d6a-24bd-4b4d-9edf-2f42147d5e64" />

## Type of change

Please delete options that are not relevant.

- [x] Bug fix

## Checklist

- [ ] “Hotfix” to `testnet`, everything else to `staging`
- [ ] Linked to Github Issue
- [ ] This change depends on code or research by an external entity
  - [ ] Acknowledgements were updated to give credit
- [ ] Unit tests added
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.
- [ ] This change is an Optimization
  - [ ] Benchmarks added/run
- [ ] Has a known issue
  - [Link to the open issue addressing it]() 
- [ ] If your PR changes the Operator compatibility (Ex: Upgrade prover versions)
  - [ ] This PR adds compatibility for operator for both versions and do not change batcher/docs/examples
  - [ ] This PR updates batcher and docs/examples to the newer version. This requires the operator are already updated to be compatible

2025-01-02 16:22 UTC, avilagaston9 commented on core/chainio/avs_subscriber.go
> +				sub, err = SubscribeToNewTasksV2Retryable(&bind.WatchOpts{}, s.AvsContractBindings.ServiceManager, internalChannel, nil, retry.SubscribeToNewTasksParams())
Aren't we missing the same change with the fallback?

2025-01-02 16:25 UTC, avilagaston9 commented on core/chainio/avs_subscriber.go
> +				sub, err = SubscribeToNewTasksV2Retryable(&bind.WatchOpts{}, s.AvsContractBindings.ServiceManager, internalChannel, nil, retry.SubscribeToNewTasksParams())
We are missing the same change with the fallback right?

2025-01-02 16:28 UTC, avilagaston9 commented on core/chainio/retryable.go
> +- Retry times (Infinite Retries): 1 sec, 2 sec, 4 sec, 8 sec, ..., 60 sec, ...,
We should update `SubscribeToNewTasksV2Retryable` comments as well

2025-01-02 16:31 UTC, avilagaston9 commented on core/retry.go
> +	// Retry Parameters for SubscribeToNewTasksV3
```suggestion
	// Retry Parameters for SubscribeToNewTasks
```

2025-01-02 16:41 UTC, PatStiles commented on core/retry.go
> +	// Retry Parameters for SubscribeToNewTasksV3
addressed!

2025-01-02 16:41 UTC, PatStiles commented on core/chainio/retryable.go
> +- Retry times (Infinite Retries): 1 sec, 2 sec, 4 sec, 8 sec, ..., 60 sec, ...,
addressed!

2025-01-02 16:41 UTC, PatStiles commented on core/chainio/avs_subscriber.go
> +				sub, err = SubscribeToNewTasksV2Retryable(&bind.WatchOpts{}, s.AvsContractBindings.ServiceManager, internalChannel, nil, retry.SubscribeToNewTasksParams())
Great Catch! Addressed!

2025-01-02 17:02 UTC, avilagaston9 approved these changes
Works in my machine! Maybe we should add logs for each retry to warn that we are trying to reconnect. Otherwise, it might seem like nothing is happening.

2025-01-02 17:29 UTC, PatStiles commented
> Works in my machine! Maybe we should add logs for each retry to warn that we are trying to reconnect. Otherwise, it might seem like nothing is happening.

Agreed! @JuArce should we do this in a separate pr.

2025-01-06 17:15 UTC, MauroToscano requested changes
I'm not convinced not shutting down is the best solution. I'm putting this on hold until the description tells in which scenario the subscription is retrying for a long time but the node is working

2025-01-09 23:54 UTC, PatStiles commented
Closing in favor of #1729

2025-01-10 00:24 UTC, closed without merging