Fix telemetry traces race condition
yetanotherco/aligned_layer pull request #1694
Opened 2024-12-30 21:58 UTC by JulianVentura

# Fix telemetry race condition

## Description

On telemetry, we are storing active traces information on the `TraceStore`. This module implements an Agent which allow us to make crud operations to the traces. The problem with this is that those operations are not atomic, so if more than one tracing message is received by telemetry at the same time and for the same merkle root, then a write on write conflict may occur while trying to modify the trace information or when setting the current trace context for OpenTelemetry.

This PR fixes this by refactoring the `traces.ex` module, implementing a GenServer, which proceses each tracing message sequentially, eliminating the race condition.

### How to test

#### Happy path

1. Start all services
2. Send some proofs
3. Check that traces are correctly generated on Jaeger.
4. Check that metrics are correctly updated on Grafana

TODO: Keep adding testing scenarios

## Type of change

Please delete options that are not relevant.

- [ ] New feature
- [X] Bug fix
- [ ] Optimization
- [X] Refactor

## Checklist

- [ ] “Hotfix” to `testnet`, everything else to `staging`
- [ ] Linked to Github Issue
- [ ] This change depends on code or research by an external entity
  - [ ] Acknowledgements were updated to give credit
- [ ] Unit tests added
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.
- [ ] This change is an Optimization
  - [ ] Benchmarks added/run
- [ ] Has a known issue
  - [Link to the open issue addressing it]() 
- [ ] If your PR changes the Operator compatibility (Ex: Upgrade prover versions)
  - [ ] This PR adds compatibility for operator for both versions and do not change batcher/docs/examples
  - [ ] This PR updates batcher and docs/examples to the newer version. This requires the operator are already updated to be compatible

2025-01-02 14:20 UTC, avilagaston9 commented on telemetry_api/lib/telemetry_api/traces.ex
> +      root_span_ctx =
```suggestion
      Ctx.clear()
      root_span_ctx =
```

2025-01-02 15:19 UTC, JulianVentura commented on telemetry_api/lib/telemetry_api/traces.ex
> +      root_span_ctx =
That seems to fix the bug. Great!

2025-01-02 19:26 UTC, PatStiles approved these changes

2025-01-02 21:57 UTC, avilagaston9 approved these changes
Works as expected! Left a nit comment

2025-01-02 21:57 UTC, avilagaston9 commented on telemetry_api/lib/telemetry_api/traces.ex
> +        {:reply, {:error, unknown}, traces}
We can have something like:
```Elixir
error -> handle_error(error)
```
To avoid repeating this logic everywhere.

2025-01-03 14:12 UTC, JulianVentura commented on telemetry_api/lib/telemetry_api/traces.ex
> +        {:reply, {:error, unknown}, traces}
Sure! I can add that if it makes it clearer

2025-01-03 15:07 UTC, JulianVentura commented on telemetry_api/lib/telemetry_api/traces.ex
> +        {:reply, {:error, unknown}, traces}
Done!

2025-01-06 15:41 UTC, JuArce reviewed
Working, I'm reviewing the code

2025-01-06 17:01 UTC, JuArce approved these changes

2025-01-06 17:04 UTC, JuArce requested changes
Check the solution with @Oppen

2025-01-06 18:35 UTC, Oppen approved these changes

2025-01-06 20:22 UTC, JuArce approved these changes

2025-01-07 15:14 UTC, merged