feat: check if batch is already responded
yetanotherco/aligned_layer pull request #174
Opened 2024-05-17 18:26 UTC by JuArce

respondToTask method now checks if batch was already responded

To test you can duplicate lines 200-203 from `aggregator/internal/pkg/aggregator.go`
``` go
	_, err := agg.avsWriter.SendAggregatedResponse(context.Background(), batchMerkleRoot, nonSignerStakesAndSignature)
	if err != nil {
		agg.logger.Error("Aggregator failed to respond to task", "err", err)
	}
```
So the second time it tries to respond the task, the service manager will revert the transaction

2024-05-20 14:36 UTC, srosati approved these changes
lgtm

2024-05-22 17:36 UTC, uri-99 requested changes
👀

2024-05-22 17:36 UTC, uri-99 commented on contracts/src/core/AlignedLayerServiceManager.sol
> +        batchesState[batchMerkleRoot].responded = true;
This line should be right after the `require` statement it is involved in (line 104), to follow CEI pattern and thus avoid possible re-entrancy attacks.
Even though this function has not much value to be exploited with a reentrancy, it is always a good idea to follow precaution and safety patterns 👍

2024-05-22 19:06 UTC, srosati approved these changes

2024-05-22 20:30 UTC, uri-99 approved these changes
👍

2024-05-23 13:26 UTC, merged