feat: operator implement merkle root ffi
yetanotherco/aligned_layer pull request #189
Opened 2024-05-22 15:23 UTC by NicolasRampoldi

# Description
- This PR adds the Merkle Root verifier FFI.
- To test, run: 
  - Rust test: `make test_merkle_tree_rust_ffi`.
  - Finally, run make `test_merkle_tree_go_bindings_macos` or make `test_merkle_tree_go_bindings_linux` depending on your OS to test the go bindings.

2024-05-22 15:36 UTC, taturosati requested changes

2024-05-22 15:36 UTC, taturosati commented on Makefile
> +	@cd operator/sp1/lib && cargo build --release
shouldn't this be merkle_tree
```suggestion
	@cd operator/merkle_tree/lib && cargo build --release
```

2024-05-22 15:36 UTC, taturosati commented on operator/merkle_tree/lib/src/types/mod.rs
Couldn't this be imported from batcher?

2024-05-22 15:40 UTC, NicolasRampoldi commented on Makefile
> +	@cd operator/sp1/lib && cargo build --release
Solved in [9be72b4](https://github.com/yetanotherco/aligned_layer/pull/189/commits/9be72b4be3c5920a040e2e3e899864bb798c5ee0).

2024-05-22 17:29 UTC, NicolasRampoldi commented on operator/merkle_tree/lib/src/types/mod.rs
Solved in [9301abb](https://github.com/yetanotherco/aligned_layer/pull/189/commits/9301abbdf9220494b2be3f0869f741e4dd4831d9).

2024-05-22 18:35 UTC, srosati approved these changes
lgtm

2024-05-23 20:02 UTC, jotabulacios approved these changes
lgtm

2024-05-23 20:03 UTC, merged