refactor: batcher create a shared crate between the cli and the batcher
yetanotherco/aligned_layer pull request #233
Opened 2024-05-29 16:45 UTC by NicolasRampoldi

# Description

- WIP.

2024-05-30 15:19 UTC, MauroToscano approved these changes

2024-05-30 20:30 UTC, uri-99 requested changes

2024-05-30 20:30 UTC, uri-99 commented on batcher/aligned-batcher-client/generate_proof_and_send.sh
> +./batcher/aligned-batcher-client/target/release/batcher-client \
run with cargo run plase :)

2024-05-31 14:27 UTC, NicolasRampoldi commented on batcher/aligned-batcher-client/generate_proof_and_send.sh
> +./batcher/aligned-batcher-client/target/release/batcher-client \
We should change that in another PR

2024-05-31 16:50 UTC, uri-99 approved these changes
worked for me

2024-06-11 19:08 UTC, merged