docs to generate GnarkPlonk proofs
yetanotherco/aligned_layer pull request #242
Opened 2024-05-29 19:59 UTC by jotabulacios

## How to test

After generating the proof, you will have to have three different files:
 - proof file
 - verification key file
 - public input file

 Then, you can send the proof to the AlignedLayer network by running the following command
 from `batcher/client` folder inside the AlignedLayer repository directory:

 ```bash
 cargo run --release -- \
 --proving_system GnarkPlonkBn254 \
 --proof <proof_path> \
 --public_input <public_input_path> \
 --vk <verification_key_path> \
 ```

2024-05-29 20:02 UTC, jotabulacios commented on README.md
> +- gnark project to generate the proofs,  instructions[ here](https://docs.gnark.consensys.io/category/how-to)
I'm not sure if this guide is the best for generating a proof. Maybe we could add a HackMD 
https://hackmd.io/@xr7wfZ30Q3eKDrtinAJaOQ/B1cp2nV4A

2024-06-04 21:11 UTC, MauroToscano commented
change the Docs file to docs/gnark_example.md, then link it in the readme

2024-06-04 21:12 UTC, MauroToscano requested changes
change the Docs file to docs/gnark_example.md, then link it in the readme

2024-06-10 15:57 UTC, MauroToscano requested changes
- Gnark version should be pinned to the one we use in Aligned, not latest
- We already have a section for sending Gnark Proofs, we can add the new data to that one. The important part is to mention you have to add code to your circuit to export the data Aligned needs. We can link the guide on how to do so

2024-10-31 18:12 UTC, Oppen commented
Converted to draft due to not being a priority for mainnet

2025-09-05 17:53 UTC, MauroToscano commented
Stale

2025-09-05 17:53 UTC, closed without merging