chore(ci): Add Risc Zero ci Test
yetanotherco/aligned_layer pull request #269
Opened 2024-05-31 09:22 UTC by PatStiles

Adds a ci test for building the risc zero go bindings.

2024-05-31 15:10 UTC, NicolasRampoldi requested changes
Ignore this, I left a wrong comment and can't delete it. My correct comment is below.

2024-05-31 15:10 UTC, NicolasRampoldi requested changes

2024-05-31 15:10 UTC, NicolasRampoldi commented on .github/workflows/test-risc-zero.yml
> +        - name: Test SP1 go bindings
Should be Test Risc Zero go bindings

2024-05-31 20:07 UTC, PatStiles commented on .github/workflows/test-risc-zero.yml
> +        - name: Test SP1 go bindings
Addressed!

2024-06-03 18:23 UTC, MauroToscano approved these changes

2024-06-03 18:23 UTC, NicolasRampoldi approved these changes

2024-06-03 18:28 UTC, merged