feat: add util to wait for transaction receipt
yetanotherco/aligned_layer pull request #36
Opened 2024-04-25 21:14 UTC by NicolasRampoldi

- Added util in `core/utils/eth_client_utils.go` to wait for transaction receipt.

2024-04-25 21:28 UTC, MauroToscano commented
We need to add this to the operator too

2024-04-26 13:16 UTC, NicolasRampoldi commented
> We need to add this to the operator too

Perfect. When the operator is pushed to main I will add it there too 👍

2024-04-26 20:07 UTC, JuArce approved these changes

2024-04-26 20:22 UTC, MauroToscano commented
> > We need to add this to the operator too
> 
> Perfect. When the operator is pushed to main I will add it there too 👍

I meant in the deposit into strategy

2024-04-26 22:10 UTC, JuArce requested changes

2024-04-26 22:10 UTC, JuArce commented on core/utils/eth_client_utils.go
> +	common2 "github.com/ethereum/go-ethereum/common"
Import this as `gethcommon` for better readibiity

2024-04-29 13:51 UTC, JuArce approved these changes

2024-04-29 15:54 UTC, srosati approved these changes
Create an issue to add max retries

2024-04-29 18:05 UTC, merged