feat: add verify function in service manager to check proof merkle path
yetanotherco/aligned_layer pull request #367
Opened 2024-06-11 22:48 UTC by entropidelic

2024-06-12 20:03 UTC, jotabulacios submitted a review, later dismissed
lgtm.
verified all proofs, and they failed as expected when data changed

2024-06-13 15:25 UTC, NicolasRampoldi approved these changes, later dismissed
lgtm, tested and it works. I made an issue #377 related to the expect in the verify function but is not related to this PR, it was from before.

2024-06-14 14:48 UTC, NicolasRampoldi approved these changes

2024-06-14 15:34 UTC, MauroToscano commented on README.md
> +--chain holesky
```suggestion
aligned verify-proof-onchain \
--aligned-verification-data <path_to_batch_verification_data> \
--private-key-store <path_to_private_key_store> \
--chain holesky
```

2024-06-14 17:57 UTC, srosati approved these changes
lgtm

2024-06-14 18:07 UTC, MauroToscano commented on README.md
> +### Verify proof batch inclusion on Ethereum
```suggestion
### Creating a transaction from the CLI to verify proof in Ethereum
```

2024-06-14 19:02 UTC, uri-99 requested changes

2024-06-14 19:02 UTC, uri-99 commented on contracts/src/core/AlignedLayerServiceManager.sol
> +            "Batch doesn't exists"
```suggestion
            "Batch doesn't exist"
```

2024-06-14 19:19 UTC, uri-99 approved these changes

2024-06-14 19:21 UTC, JuArce approved these changes

2024-06-14 19:50 UTC, merged