feat: explorer extend database to relieve rpc calls
yetanotherco/aligned_layer pull request #382
Opened 2024-06-13 19:25 UTC by uri-99

2024-06-18 15:40 UTC, MauroToscano approved these changes

2024-06-19 15:43 UTC, NicolasRampoldi requested changes

2024-06-19 15:43 UTC, NicolasRampoldi commented on explorer/.env.example
> +ALIGNED_CONFIG_FILE="<aligned_config_file>"
Missing new line

2024-06-19 15:43 UTC, NicolasRampoldi commented on explorer/lib/explorer/aligned_layer_service_manager.ex
>        "mainnet" -> 20020000
I think we should add holesky stage here. Also, it would be nice if we could set this in environment variables

2024-06-19 15:43 UTC, NicolasRampoldi commented on explorer/lib/scripts/fetch_old_batches.ex
> +    chunk_size = 3 #do in smaller chunks, if there are too many blocks to process
Maybe the chunk size could be parametrized

2024-06-20 16:51 UTC, uri-99 commented on explorer/lib/explorer/aligned_layer_service_manager.ex
>        "mainnet" -> 20020000
This separation was develpoed but not really useful, both use holesky so separating holesky stage and holesky prod initial blocks is not currently necesarry, both use the same values

2024-06-20 18:07 UTC, NicolasRampoldi approved these changes

2024-06-20 18:31 UTC, merged