docs: use aligned on your app
yetanotherco/aligned_layer pull request #513
Opened 2024-06-27 17:34 UTC by srosati

Documentation specifying how to integrate your app with Aligned.

2024-06-28 19:54 UTC, uri-99 requested changes

2024-06-28 19:54 UTC, uri-99 commented on docs/guides/2_using_aligned_on_your_app.md
> +
I would something add the end as a wrap-up to the guide

2024-06-28 19:54 UTC, uri-99 commented on docs/guides/2_using_aligned_on_your_app.md
> +require(elfCommitment == provingSystemAuxDataCommitment, "ELF does not match");```
remove extra ` ``` `
```suggestion
require(elfCommitment == provingSystemAuxDataCommitment, "ELF does not match");
```

2024-06-28 19:54 UTC, uri-99 commented on docs/guides/2_using_aligned_on_your_app.md
> +to check that the proof was verified in Aligned.
```suggestion
to check that the proof was verified in Aligned. For a full version of this, you can view, use as an example guide, or inherit the [Verify Batch Inclusion Caller](../../examples/verify/src/VerifyBatchInclusionCaller.sol) smart contract.
```

2024-07-01 17:50 UTC, uri-99 approved these changes

2024-07-01 19:10 UTC, NicolasRampoldi approved these changes

2024-07-01 19:39 UTC, merged