docs: add more explanations on how to integrate aligned
yetanotherco/aligned_layer pull request #582
Opened 2024-07-04 17:39 UTC by JuArce

2024-07-04 17:42 UTC, srosati commented on docs/SUMMARY.md
> +* [Integration Aligned into your Application](guides/2_integration_aligned_into_your_application)
```suggestion
* [Integrating Aligned into your Application](guides/2_integration_aligned_into_your_application)
```

2024-07-04 17:54 UTC, glpecile requested changes

2024-07-04 17:54 UTC, glpecile commented on docs/guides/2_integration_aligned_into_your_application.md
> +An example [python script](../../examples/zkquiz/encode_verification_data.py) can be found to encode the call data from the json output of the Aligned cli.
CLI

2024-07-04 17:54 UTC, glpecile commented on docs/guides/2_integration_aligned_into_your_application.md
> +An example [python script](../../examples/zkquiz/encode_verification_data.py) can be found to encode the call data from the json output of the Aligned cli.
Remove space.

2024-07-04 17:54 UTC, glpecile commented on docs/guides/2_integration_aligned_into_your_application.md
> +```bash
Add \n

2024-07-04 17:54 UTC, glpecile commented on docs/guides/2_integration_aligned_into_your_application.md
> +```solidity
Add \n

2024-07-04 17:54 UTC, glpecile commented on docs/guides/2_integration_aligned_into_your_application.md
> +You can find the example of the quiz proof [program](../../examples/zkquiz/quiz/program/src/main.rs) as well as the [script](../../examples/zkquiz/quiz/script/src/main.rs) that generates it in the [Z
an example

2024-07-04 17:54 UTC, glpecile commented on docs/guides/2_integration_aligned_into_your_application.md
> +The aligned cli provides a way for you to get the verification key commitment
Aligned CLI

2024-07-04 17:54 UTC, glpecile commented on docs/guides/2_integration_aligned_into_your_application.md
> +Note that the contract checks that the verification key commitment is the same as the program elf.
ELF

2024-07-04 17:54 UTC, glpecile commented on docs/guides/2_integration_aligned_into_your_application.md
> +to check that the proof was verified in Aligned.
if

2024-07-04 17:54 UTC, glpecile commented on docs/guides/2_integration_aligned_into_your_application.md
> +For SP1 this means having the [script](../../examples/zkquiz/quiz/script/src/main.rs)
Add ,

2024-07-04 17:54 UTC, glpecile commented on docs/guides/2_integration_aligned_into_your_application.md
> +You can find examples of how to submit a proof using the cli
CLI

2024-07-04 17:54 UTC, glpecile commented on docs/guides/2_integration_aligned_into_your_application.md
> +An example [python script](../../examples/zkquiz/encode_verification_data.py) can be found to encode the call data from the json output of the Aligned cli.
JSON

2024-07-04 22:22 UTC, glpecile commented on docs/guides/2_integration_aligned_into_your_application.md
> +The example generates a proof, instantiate a wallet to submit the proof, and then submits the proof to Aligned for verification. It then waits for the proof to be verified in Aligned.
```suggestion
The example generates a proof, instantiates a wallet to submit the proof, and then submits the proof to Aligned for verification. It then waits for the proof to be verified in Aligned.
```

2024-07-05 19:57 UTC, srosati approved these changes

2024-07-05 20:03 UTC, glpecile requested changes

2024-07-05 20:03 UTC, glpecile commented on docs/guides/2_integration_aligned_into_your_application.md
> +The aligned CLI provides a way for you to get the verification key commitment without actually generating and submitting a proof.
```suggestion
The Aligned CLI provides a way for you to get the verification key commitment without actually generating and submitting a proof.
```

2024-07-05 20:03 UTC, glpecile commented on docs/guides/2_integration_aligned_into_your_application.md
> +You can find the example of the smart contract that checks the proof was verified in Aligned in the [Quiz Verifier Contract](../../examples/zkquiz/contracts/src/VerifierContract.sol).
```suggestion
You can find an example of the smart contract that checks if the proof was verified in Aligned in the [Quiz Verifier Contract](../../examples/zkquiz/contracts/src/VerifierContract.sol).
```

2024-07-05 20:03 UTC, glpecile commented on docs/guides/2_integration_aligned_into_your_application.md
> +Note that the contract checks that the verification key commitment is the same as the program elf.
```suggestion
Note that the contract checks that the verification key commitment is the same as the program ELF.
```

2024-07-05 20:03 UTC, glpecile commented on docs/guides/2_integration_aligned_into_your_application.md
> +To submit a proof using the SDK, you can use the `submit` function, and then you can use the `verify_proof_onchain` to check if the proof was correctly verified in Aligned.
```suggestion
To submit a proof using the SDK, you can use the `submit` function, and then you can use the `verify_proof_onchain` function to check if the proof was correctly verified in Aligned.
```

2024-07-08 14:13 UTC, glpecile approved these changes
LGTM 👍

2024-07-08 16:03 UTC, entropidelic commented on docs/guides/2_integration_aligned_into_your_application.md
> +This example shows a sample app that generates an SP1 proof that a user knows the answers to a quiz, then submits the proof to Aligned for verification. Finally, it includes a smart contract that ver
```suggestion
This example shows a sample app that generates an SP1 proof that a user knows the answers to a quiz and then submits the proof to Aligned for verification. Finally, it includes a smart contract that verifies that a proof was verified in Aligned and mints an NFT.
```

2024-07-08 16:05 UTC, entropidelic commented on docs/guides/2_integration_aligned_into_your_application.md
> +To check if a proof was verified in Aligned, you need to call to the Aligned ServiceManager contract inside your smart contract.
```suggestion
To check if a proof was verified in Aligned, you need to make a call to the Aligned ServiceManager contract inside your smart contract.
```

2024-07-08 16:06 UTC, entropidelic commented on docs/guides/2_integration_aligned_into_your_application.md
> +Also, you will need a way to check that the proven program is your own.
```suggestion
Also, you will need a way to check that the proven program is the correct one.
```

2024-07-08 16:09 UTC, entropidelic commented on docs/guides/2_integration_aligned_into_your_application.md
> +Note that the contract checks that the verification key commitment is the same as the program ELF.
```suggestion
Note that the contract checks that the verification key commitment is the same as the program ELF commitment.
```

2024-07-08 16:40 UTC, entropidelic commented on docs/guides/2_integration_aligned_into_your_application.md
> +You can find an example of the quiz proof [program](../../examples/zkquiz/quiz/program/src/main.rs) as well as the [script](../../examples/zkquiz/quiz/script/src/main.rs) that generates it in the [ZK
This section is a little confusing for someone with no context. The rust code seems to be like a shorter version of the program to generate the proof in `../../examples/zkquiz/quiz/script/src/main.rs`. If we add this code we should add some more context (like why are we showing this code in the first place?) and exaplanation of what is happening

2024-07-10 12:46 UTC, JuArce commented on docs/guides/2_integration_aligned_into_your_application.md
> +You can find an example of the quiz proof [program](../../examples/zkquiz/quiz/program/src/main.rs) as well as the [script](../../examples/zkquiz/quiz/script/src/main.rs) that generates it in the [ZK
I agree. I will add an explanation on every code section

2024-07-10 18:44 UTC, glpecile requested changes

2024-07-10 18:44 UTC, glpecile commented on docs/SUMMARY.md
> +* [Integrating Aligned into your Application](guides/2_integration_aligned_into_your_application.md)
```suggestion
* [Integrating Aligned into your Application](guides/2_integrating_aligned_into_your_application.md)
```

2024-07-10 18:44 UTC, glpecile commented on docs/guides/2_integration_aligned_into_your_application.md
Change name to `2_integrating_aligned_into_your_application.md`

2024-07-10 18:44 UTC, glpecile commented on docs/guides/2_integration_aligned_into_your_application.md
> +You can find examples of how to generate proofs in the [generating proofs guide](3_generating_proofs.md).
```suggestion
You can find examples on how to generate proofs in the [generating proofs guide](3_generating_proofs.md).
```

2024-07-10 18:44 UTC, glpecile commented on docs/guides/2_integration_aligned_into_your_application.md
> +Also you can find an example of the ZKQuiz proof [program](../../examples/zkquiz/quiz/program/src/main.rs) as well as the [script](../../examples/zkquiz/quiz/script/src/main.rs) that generates it in
```suggestion
Also you can find an example of the ZKQuiz proof [program](../../examples/zkquiz/quiz/program/src/main.rs) as well as the [script](../../examples/zkquiz/quiz/script/src/main.rs) that generates it in the [ZKQuiz example directory](../../examples/zkquiz).
```

2024-07-10 18:44 UTC, glpecile commented on docs/guides/2_integration_aligned_into_your_application.md
> +The following is an example of how to call the `verifyBatchInclusionMethod` from the Aligned ServiceManager contract in your smart contract.
```suggestion
The following is an example of how to call the `verifyBatchInclusionMethod` from the `AlignedServiceManager` contract in your smart contract.
```

2024-07-10 18:44 UTC, glpecile commented on docs/guides/2_integration_aligned_into_your_application.md
> +Note that the contract checks that the verification key commitment is the same as the program ELF commitment.
```suggestion
Note that the contract checks if the verification key commitment is the same as the program ELF commitment.
```

2024-07-10 18:44 UTC, glpecile commented on docs/guides/2_integration_aligned_into_your_application.md
> +This contract also includes a static call to the Aligned ServiceManager contract to check if the proof was verified in Aligned.
```suggestion
This contract also includes a static call to the `AlignedServiceManager` contract to check if the proof was verified in Aligned.
```

2024-07-10 18:44 UTC, glpecile commented on docs/guides/2_integration_aligned_into_your_application.md
> +The example generates a proof, instantiates a wallet to submit the proof, and then submits the proof to Aligned for verification. It then waits for the proof to be verified in Aligned.
```suggestion
This example generates a proof, instantiates a wallet to submit the proof, and then submits the proof to Aligned for verification. Lastly, it waits for the proof to be verified in Aligned.
```

2024-07-10 21:46 UTC, glpecile approved these changes

2024-07-10 21:50 UTC, merged