refactor: rename get-vk-commitment to get-commitment
yetanotherco/aligned_layer pull request #608
Opened 2024-07-08 20:08 UTC by srosati

To make it generic for both verification keys and public inputs.

# To test
Install aligned cli
```bash
make install_aligned_compiling
```

Get commitment for file
```bash
aligned get-commitment --input ./scripts/test_files/sp1/sp1_fibonacci.elf
```

2024-07-08 20:11 UTC, NicolasRampoldi requested changes
I think we should change it in the sdk too

2024-07-08 20:22 UTC, NicolasRampoldi approved these changes

2024-07-10 13:55 UTC, entropidelic commented on batcher/aligned-sdk/src/sdk.rs
>  /// * None.
lets change the commented code too

2024-07-10 16:02 UTC, srosati commented on batcher/aligned-sdk/src/sdk.rs
>  /// * None.
Changed

2024-07-10 18:22 UTC, JuArce approved these changes

2024-07-10 20:00 UTC, entropidelic approved these changes

2024-07-10 20:21 UTC, merged