chore: add LocalStack for local s3
yetanotherco/aligned_layer pull request #647
Opened 2024-07-17 23:37 UTC by JuArce

# How to test
1. Run anvil, operator and aggregator
2. Run docker
3. Run `make run_storage`. It will run an s3 bucket in a docker container
4. Run `make batcher_start_local`. It will use the `.env.local` file with the local bucket credentials
5. Send proofs and check everything is working

2024-07-18 21:04 UTC, NicolasRampoldi requested changes
The .env.example is missing the ENVIRONMENT and STORAGE_ENDPOINT en variables.

2024-07-18 21:04 UTC, NicolasRampoldi commented on storage-docker-compose.yaml
> +version: "3.8"
This version tag is no longer needed in docker compose https://forums.docker.com/t/docker-compose-yml-version-is-obsolete/141313/3

2024-07-19 01:03 UTC, uri-99 requested changes
Only some small details, functionality worked

2024-07-19 01:03 UTC, uri-99 commented on batcher/aligned-batcher/.env.example
> +ENVIRONMENT=<local|prod>
```suggestion
ENVIRONMENT=<dev|prod>
```

2024-07-19 01:03 UTC, uri-99 commented on batcher/aligned-batcher/.env.local
> +ENVIRONMENT=local
```suggestion
ENVIRONMENT=dev
```

2024-07-19 01:03 UTC, uri-99 commented on batcher/aligned-batcher/src/s3/mod.rs
> +const LOCALSTACK_ENDPOINT: &str = "http://127.0.0.1:4566/";
Can't we read this from .env?
Doesn't seem right to have a hardcoded dev value in the same batcher we'll send to prod

2024-07-19 01:03 UTC, uri-99 commented on batcher/aligned-batcher/.env.local
I think we should rename this to .env.dev , as there is another another similar .env (used only for devs) in the codebase, named env.dev

2024-07-19 01:33 UTC, uri-99 commented on Makefile
> +	@cargo +nightly-2024-04-17 run --manifest-path ./batcher/aligned-batcher/Cargo.toml --release -- --config ./config-files/config-batcher.yaml --env-file ./batcher/aligned-batcher/.env.local
We could also make batcher_start_local run the local s3 as well:

```suggestion
batcher_start_local: ./batcher/aligned-batcher/.env user_fund_payment_service
        @echo "Starting local_db"
        @$(MAKE) run_storage &
	@echo "Starting Batcher..."
	@cargo +nightly-2024-04-17 run --manifest-path ./batcher/aligned-batcher/Cargo.toml --release -- --config ./config-files/config-batcher.yaml --env-file ./batcher/aligned-batcher/.env.local
```

2024-07-19 15:55 UTC, entropidelic commented on batcher/aligned-batcher/src/s3/mod.rs
> +    }
this will always return true hehe :). What are you checking here? If you want to check if `endpoint_url` is `Some`, you already did in line 12.

2024-07-29 17:44 UTC, NicolasRampoldi approved these changes

2024-07-30 20:04 UTC, uri-99 approved these changes

2024-08-01 19:53 UTC, merged