feat(explorer): add validator screen
yetanotherco/aligned_layer pull request #651
Opened 2024-07-19 18:06 UTC by glpecile

2024-08-15 17:44 UTC, uri-99 approved these changes

2024-08-19 17:37 UTC, NicolasRampoldi requested changes

2024-08-19 17:37 UTC, NicolasRampoldi commented on explorer/lib/explorer/contract_managers/delegation_manager.ex
> +      |> Ethers.get_logs(fromBlock: 0)
Maybe we can start it in a higher number, I don't think it's necessary to parse every block

2024-08-19 17:37 UTC, NicolasRampoldi commented on explorer/lib/explorer/contract_managers/delegation_manager.ex
> +  # this gets of all eigenlayer, not avs. sad
Delete comment

2024-08-20 20:32 UTC, NicolasRampoldi approved these changes

2024-08-22 15:58 UTC, entropidelic commented on explorer/lib/explorer/contract_managers/aligned_layer_service_manager.ex
> +        dbg("Error fetching restakeable stratergies: #{error}")
```suggestion
        dbg("Error fetching restakeable strategies: #{error}")
```

2024-08-22 15:59 UTC, entropidelic commented on explorer/lib/explorer/contract_managers/aligned_layer_service_manager.ex
> +        raise("Error fetching restakeable stratergies: #{error}")
```suggestion
        raise("Error fetching restakeable strategies: #{error}")
```

2024-08-22 16:12 UTC, entropidelic commented on explorer/lib/explorer/contract_managers/stake_registry_manager.ex
> +  end
```suggestion
  end
  
```

2024-08-22 17:49 UTC, entropidelic approved these changes

2024-08-23 20:04 UTC, uri-99 requested changes
not yet

2024-08-23 21:11 UTC, uri-99 approved these changes

2024-08-23 21:12 UTC, merged