fix: nonce handling
yetanotherco/aligned_layer pull request #669
Opened 2024-07-25 17:06 UTC by srosati

# Implementation

Implement nonce cache clearing on fail, both on client and on batcher

![image](https://github.com/user-attachments/assets/5dd48102-5837-4b2a-8f3e-e4ee27b31cde)

# To test

Test normal flow, make some txs revert by sending same burst twice

2024-07-25 17:43 UTC, MauroToscano commented on batcher/aligned-batcher/src/lib.rs
> +    async fn reset_state(&self) {
```suggestion
    async fn flush_queue_and_clear_nonce_cache(&self) {
```

2024-07-26 12:56 UTC, srosati commented on batcher/aligned-batcher/src/lib.rs
> +    async fn reset_state(&self) {
changed on 7700d8197cd52aacb695bb885f428f741532665a

2024-07-26 16:18 UTC, uri-99 requested changes
If a tx reverts because of invalid nonce, batcher will try to send the same tx to blockchain ~50 times before it stops trying. It should try only once or twice, because no variable is changing between retries.

The following error appeared every times in the batcher when sending concurrent proofs
`ERROR aligned_batcher] Error while sending batch inclusion data response: IO error: Broken pipe (os error 32)`

Batcher gets the following error when trying to send second message to client
`Unexpected error: IO error: Connection reset by peer (os error 54)`

2024-07-28 15:35 UTC, MauroToscano approved these changes

2024-07-29 14:25 UTC, uri-99 approved these changes
I understand my previous comments should be addressed in another PR

2024-07-29 17:10 UTC, merged