feat: fallback rpc on operator and aggregator
yetanotherco/aligned_layer pull request #731
Opened 2024-08-06 18:34 UTC by srosati

Add required fallback rpc url on operator and aggregator (added on core)

For subscriber, two subscriptions are made but events are only forwarded once.

2024-08-06 20:15 UTC, NicolasRampoldi commented on config-files/config-operator.yaml
> +eth_ws_url_fallback: "ws://localhost:8545"
This was:
```
eth_rpc_url: "https://ethereum-holesky-rpc.publicnode.com"
eth_ws_url: "wss://ethereum-holesky-rpc.publicnode.com"
```
before and now it's localhost

2024-08-06 20:57 UTC, NicolasRampoldi commented on core/chainio/avs_subscriber.go
> +		// try with the fallback client
Maybe we can add a log here that it's trying with the fallback client? If it will get too spammy then don't

2024-08-07 18:29 UTC, JuArce approved these changes

2024-08-07 18:29 UTC, JuArce commented on config-files/config-operator-1.yaml
> +eth_rpc_url_falback: "http://localhost:8545"
```suggestion
eth_rpc_url_fallback: "http://localhost:8545"
```

2024-08-07 18:29 UTC, JuArce commented on config-files/config-operator-1.yaml
> +eth_ws_url_falback: "ws://localhost:8545"
```suggestion
eth_ws_url_fallback: "ws://localhost:8545"
```

2024-08-07 18:29 UTC, JuArce commented on core/chainio/avs_subscriber.go
> +	errChan := make(chan error)
This is unnecessary

2024-08-07 18:51 UTC, JuArce requested changes
Testing in stage

2024-08-08 19:38 UTC, entropidelic approved these changes

2024-08-09 16:09 UTC, JuArce approved these changes

2024-08-09 16:31 UTC, merged