feat(explorer): add search by proof hash
yetanotherco/aligned_layer pull request #766
Opened 2024-08-09 23:06 UTC by glpecile

# Changes

* add method to proofs API that returns the merkle root of the batch that contains proof hash hex
* add method call to search live component

2024-08-12 15:21 UTC, uri-99 requested changes
This PR is missing a view showing all batches where a proof is present, if the proof is present in more than one batch

2024-08-12 15:21 UTC, uri-99 commented on explorer/lib/explorer/models/proofs.ex
> +    case Explorer.Repo.one(query) do
This gets only the latest entry, but we can have a proof present in many batches

2024-08-27 13:50 UTC, entropidelic approved these changes

2024-08-27 14:27 UTC, uri-99 requested changes

2024-08-27 14:27 UTC, uri-99 commented on explorer/lib/explorer/models/proofs.ex
> +  def get_batch_from_proof(proof_hash_hex) do
if it returns N, function name should be plural
```suggestion
  def get_batches_containing_proof(proof_hash_hex) do
```

2024-08-27 14:27 UTC, uri-99 commented on explorer/lib/explorer_web/live/pages/search/index.ex
> +    case Proofs.get_batch_from_proof(hash) do
```suggestion
    case Proofs.get_batches_containing_proof(hash) do
```

2024-08-27 15:08 UTC, NicolasRampoldi reviewed
I think we should add pagination, other than that everything seems ok

2024-08-27 20:42 UTC, uri-99 approved these changes

2024-08-27 20:47 UTC, NicolasRampoldi approved these changes

2024-08-27 20:50 UTC, merged