feat: add build-aligned-contracts to CI
yetanotherco/aligned_layer pull request #80
Opened 2024-04-30 18:19 UTC by uri-99

2024-04-30 19:14 UTC, JuArce requested changes

2024-04-30 19:14 UTC, JuArce commented on .github/workflows/build-contracts.yml
> +      - master
we do not use master branch

2024-05-02 13:48 UTC, uri-99 commented on .github/workflows/build-contracts.yml
> +      - master
removed 👍

2024-05-02 14:44 UTC, MauroToscano approved these changes

2024-05-02 14:44 UTC, MauroToscano approved these changes

2024-05-02 14:49 UTC, entropidelic approved these changes

2024-05-02 15:11 UTC, JuArce approved these changes

2024-05-02 15:14 UTC, merged