feat: add chain id to signature for batcher payments
yetanotherco/aligned_layer pull request #822
Opened 2024-08-21 14:37 UTC by srosati

Add chain id to batcher payments to fix issue where batcher could reuse signatures across chains. 

Now user signs hash of verification data + nonce + chain id

Contract verifies with same flow

# To test

Just test normal flow

2024-08-21 17:55 UTC, NicolasRampoldi requested changes

2024-08-21 17:55 UTC, NicolasRampoldi commented on batcher/aligned-batcher/src/lib.rs
> +
If it fails we can try with the `eth_rpc_provider_fallback`

2024-08-21 18:11 UTC, srosati commented on batcher/aligned-batcher/src/lib.rs
> +
fixed on e401d33

2024-08-21 18:31 UTC, uri-99 approved these changes

2024-08-21 19:49 UTC, NicolasRampoldi approved these changes

2024-08-22 19:12 UTC, MauroToscano requested changes
Batcher should have the chainID in a config, to be able to filter signed transactions with a wrong chainID

2024-08-22 20:43 UTC, entropidelic approved these changes

2024-08-23 14:31 UTC, MauroToscano approved these changes

2024-08-23 14:31 UTC, merged