chore: add multiple operators configs
yetanotherco/aligned_layer pull request #85
Opened 2024-04-30 20:28 UTC by JuArce

# Description
Now you can register and run operators using custom config files
By default will use `config-files/config.yaml`

To pass a custom config file you have to use `CONFIG_FILE` as follows:
`make operator-start CONFIG_FILE=<path_to_file>`
`make operator-full-registration CONFIG_FILE=<path_to_file>`

If you do not set CONFIG_FILE it will use the default

2024-04-30 20:46 UTC, srosati requested changes
add docs on how to run

2024-04-30 23:20 UTC, srosati approved these changes

2024-04-30 23:34 UTC, NicolasRampoldi approved these changes

2024-05-02 14:53 UTC, MauroToscano commented
I'd add in the README the pre generated configs provided

2024-05-02 15:25 UTC, JuArce commented
> I'd add in the README the pre generated configs provided

Done, I added it in Config File section

2024-05-02 15:38 UTC, MauroToscano approved these changes

2024-05-02 15:39 UTC, merged