fix: batcher nonce verification order in handle_message function
yetanotherco/aligned_layer pull request #864
Opened 2024-08-26 19:46 UTC by NicolasRampoldi

# Description

- This PR refactors the message handling process to address the security concerns detailed in the audit.
- To achieve this, it does the following:
  1. Check the nonce before verifying the proof in both `handle_message` and `handle_nonpaying_msg`.
  2. Separate nonce checking and incrementing operations to ensure atomicity.
  3. Improve error handling and messaging for invalid nonces and proofs.

# To Test

- Test full flow with paying and non-paying address. Make sure everything is working correctly.

2024-08-26 21:15 UTC, MauroToscano requested changes
User can submit a transaction with the same nonce while the proofs are verifying and this could end up in an invalid state. The nonce needs to be blocked while this process is going.

2024-08-27 13:23 UTC, NicolasRampoldi commented
> User can submit a transaction with the same nonce while the proofs are verifying and this could end up in an invalid state. The nonce needs to be blocked while this process is going.

Solved in [aff5aac](https://github.com/yetanotherco/aligned_layer/pull/864/commits/aff5aac858c3c8f43273b6df1b8307e7453aae9a)

2024-08-27 14:21 UTC, entropidelic commented
it seems like when a createNewTask transaction is reverted, the nonce is set to an invalid state and then all proofs sent with that address get an `invalid nonce` error.
To replicate, try sending two bursts of the same proof. For example:
```
make batcher_send_risc0_burst
```
when the transaction is reverted because of the repeated merkle root, you should not be able to send any more proofs with that address

2024-08-27 18:00 UTC, NicolasRampoldi commented
> it seems like when a createNewTask transaction is reverted, the nonce is set to an invalid state and then all proofs sent with that address get an `invalid nonce` error. To replicate, try sending two bursts of the same proof. For example:
> 
> ```
> make batcher_send_risc0_burst
> ```
> 
> when the transaction is reverted because of the repeated merkle root, you should not be able to send any more proofs with that address

Solved in [ea00344](https://github.com/yetanotherco/aligned_layer/pull/864/commits/ea00344cc75b3f5ad1ecf6170b7e3d15755be995). I added a condition that thought was necessary but it didn't make sense

2024-08-27 19:32 UTC, entropidelic approved these changes

2024-09-04 18:44 UTC, taturosati commented on batcher/aligned-batcher/src/lib.rs
> +
```suggestion
```

2024-09-25 19:11 UTC, uri-99 commented
Being solved in #1087 and 'refactor-user-states'

2024-09-25 19:11 UTC, closed without merging