fix(explorer): handle empty events from batcher payment system
yetanotherco/aligned_layer pull request #888
Opened 2024-08-28 19:11 UTC by glpecile

# Changes

* update text to say fee
* add case when empty array from events and add log
* do not display batch fee that returned empty from logs

2024-08-28 21:33 UTC, uri-99 requested changes

2024-08-28 21:33 UTC, uri-99 commented on explorer/lib/explorer/contract_managers/batcher_payment_service_manager.ex
> +        Logger.error("No events found for merkle root: #{merkle_root}")
```suggestion
        Logger.error("No task_created events found on BatcherPayments for merkle root: #{merkle_root}")
```

2024-08-28 22:39 UTC, uri-99 approved these changes

2024-08-29 14:30 UTC, glpecile commented on explorer/lib/explorer/contract_managers/batcher_payment_service_manager.ex
> +        Logger.error("Unexpected response onfee per proof events: #{inspect(other)}")
```suggestion
        Logger.error("Unexpected response on fee per proof events: #{inspect(other)}")
```

2024-08-29 19:15 UTC, entropidelic commented on explorer/lib/explorer/models/batches.ex
> +    |> validate_number(:fee_per_proof, greater_than: -1)
smol nit, but I think it makes more sense
```suggestion
    |> validate_number(:fee_per_proof, :greater_than_or_equal_to: 0)
```

2024-08-29 19:16 UTC, entropidelic approved these changes

2024-08-29 19:17 UTC, merged