fix (sdk): add sender address to wait for verification function
yetanotherco/aligned_layer pull request #909
Opened 2024-08-30 14:03 UTC by taturosati

Add batcher payments service address to the following functions on the sdk:

- submit_multiple_and_wait_verification
- submit_and_wait_verification
- is_proof_verified

This is needed for change on aligned service manager where sender address was added to batch identifier.

Needs to be merged before automatic upgrade on Tuesday, then we should release this version of sdk.

2024-08-30 19:32 UTC, entropidelic approved these changes

2024-09-03 13:54 UTC, JuArce requested changes
Lgtm. Merge after block 2_268_375

2024-09-03 13:54 UTC, JuArce commented on batcher/aligned-sdk/src/sdk.rs
> +    const BATCHER_PAYMENT_SERVICE_ADDR: &str = "0x7969c5eD335650692Bc04293B07F5BF2e7A673C0";
This values is just used for tests right?

2024-09-03 14:34 UTC, uri-99 approved these changes

2024-09-04 15:07 UTC, JuArce approved these changes

2024-09-04 15:07 UTC, merged