feat(explorer): add dependabot
yetanotherco/aligned_layer pull request #925
Opened 2024-09-04 18:45 UTC by glpecile

2024-09-09 15:43 UTC, uri-99 requested changes
This should be tested on this branch before pushed to main.
This can be done by changing the target-branch, making the interval higher, injecting an old version, and then seeing if Dependabot works ok.

2024-09-11 22:14 UTC, glpecile commented on .github/dependabot.yml
> +    target-branch: "main"
```suggestion
    target-branch: "staging"
```

2024-09-11 22:19 UTC, glpecile commented
@uri-99 the image below basically shows that the config is correct and will start publishing updates once merged. 

<img width="488" alt="image" src="https://github.com/user-attachments/assets/6affc8f6-1dab-47de-8e00-67d232b9236c">

2024-10-31 18:13 UTC, Oppen commented
Converted to draft due to not being a priority for mainnet

2024-11-06 14:19 UTC, JuArce commented
Stale

2024-11-06 14:19 UTC, closed without merging