Add quorumThresholdPercentage to MainTaskSender
yetanotherco/aligned_layer pull request #95
Opened 2024-05-02 20:13 UTC by isoprophlex

Added option to customize quorumThresholdPercentage via config-file in MainTaskSender before Task is created in:
`	task := types.NewTask(provingSystem, proofFile, publicInputFile, verificationKeyFile, uint8(quorumThresholdPercentage))
`
I also added a print to check if the percentage was set correctly before sending the task.
<img width="563" alt="Captura de pantalla 2024-05-02 a la(s) 17 12 36" src="https://github.com/yetanotherco/aligned_layer/assets/86675078/3f3b0696-a34a-43c6-91b0-dc950e185903">

2024-05-02 20:37 UTC, NicolasRampoldi requested changes

2024-05-02 20:37 UTC, NicolasRampoldi commented on task_sender/cmd/main.go
> +	quorumThresholdPercentage, ok, err := getQuorumThresholdPercentage(c.String(config.ConfigFileFlag.Name)) // Read from config
Missing error check.

2024-05-02 20:37 UTC, NicolasRampoldi commented on task_sender/cmd/main.go
> +	println(quorumThresholdPercentage)
Remove

2024-05-02 21:12 UTC, NicolasRampoldi requested changes

2024-05-02 21:12 UTC, NicolasRampoldi commented on Makefile
> +		--q 25 \
Use something more descriptive instead of `q`.

2024-05-02 21:12 UTC, NicolasRampoldi commented on config-files/config.yaml
> +  quorum_threshold_percentage: 92
Remove if it is no longer being used

2024-05-03 14:44 UTC, NicolasRampoldi approved these changes

2024-05-03 15:02 UTC, entropidelic approved these changes

2024-05-03 15:02 UTC, merged