feat: add retry to get batch of s3
yetanotherco/aligned_layer pull request #958
Opened 2024-09-11 17:30 UTC by NicolasRampoldi

# Description

- This PR adds an Operator retry with an exponential backoff to get the batch of S3.
- The amount of max retries was set to `3`.
- The initial retry delay has been set to `5s`. 
- So: 5s, 10s, 20s.

# To Test

- Make sure everything works normally.
- You can replace line 34 of `operator/pkg/s3.go` with:
```go
req, err = http.NewRequestWithContext(ctx, "GET", "", nil)
```
To see how the retry works.

2024-09-11 18:12 UTC, taturosati commented on operator/pkg/s3.go
> +			o.Logger.Infof("Retrying S3 fetch (attempt %d of %d)", attempt+1, maxRetries)
nice to have, log how long will wait before retry
```suggestion
			o.Logger.Infof("Waiting for %s before retrying S3 fetch (attempt %d of %d)", retryDelay, attempt+1, maxRetries)
```

2024-09-11 18:18 UTC, taturosati approved these changes
lgtm, tested and working

2024-09-13 18:09 UTC, PatStiles approved these changes

2024-09-13 18:41 UTC, entropidelic approved these changes

2024-09-13 18:42 UTC, entropidelic requested changes
lgtm, let's try it in staging before merging

2024-09-13 22:21 UTC, uri-99 approved these changes

2024-09-16 21:15 UTC, entropidelic approved these changes

2024-09-16 21:25 UTC, merged