fix(audit): Add additional length verification to ffi bindings
yetanotherco/aligned_layer pull request #993
Opened 2024-09-17 17:14 UTC by PatStiles

Builds on the work in #738 by adding additional checks to the ffi binding interfaces. Verifies the supplied lengths match the length of the supplied buffer for proofs, params, and public inputs.

2024-09-23 20:26 UTC, MauroToscano approved these changes

2024-09-23 20:27 UTC, MauroToscano commented
Code looks good, needs to be tested

2024-09-24 15:22 UTC, uri-99 approved these changes

2024-09-24 19:37 UTC, uri-99 requested changes
blocking PR until Pat finishes some changes

2024-09-25 19:19 UTC, PatStiles commented
Closing this after discussing with @Oppen.

2024-09-25 19:19 UTC, closed without merging