fix(audit): Add Fuzzer for cbor serialization in Operator
yetanotherco/aligned_layer pull request #997
Opened 2024-09-17 21:35 UTC by PatStiles

Adds a fuzzer for cbor serialization within the operator closes #902 .

2024-09-20 19:15 UTC, MauroToscano requested changes
I'm getting ```no Go files in ../workspace/aligned_layer/operator```. We also need to document this somewhere

2024-09-23 19:56 UTC, PatStiles commented
Add make targets for fuzzing.

2024-09-24 17:32 UTC, uri-99 requested changes

2024-09-24 17:32 UTC, uri-99 commented on operator/pkg/marshall_unmarshall_test.go
> +		err := decoder.Decode(marshalled)
[Decode() must be passed a pointer](https://github.com/ugorji/go/blob/master/codec/decode.go#L1492)
```suggestion
		err := decoder.Decode(&marshalled)
```

2024-09-24 18:44 UTC, uri-99 requested changes
Fuzzer is returning an error:

<img width="886" alt="image" src="https://github.com/user-attachments/assets/e214f480-1a9c-4cfd-910a-9fcfe5fc2755">

This seems to be when Decode() is called with the data parameter: `[]byte("\xa7_[\x00\x00\x10\x000000")`

2024-09-27 17:55 UTC, uri-99 commented
Was @Oppen debugging the panic on the Decode function? Any news?

2024-09-27 22:18 UTC, uri-99 commented
Note: same crash happens on Linux

2024-09-27 23:01 UTC, IAvecilla commented
After some debugging and research, we decided to try changing the CBOR library we were using. That change seems to have fixed the issue.

I’ve opened PR #1110, which updates the library to the one proposed by @Oppen in #1093 .

2024-09-30 15:07 UTC, MauroToscano requested changes
If the data is invalid unmarshall will fatal. Just check the decoding works and doesn't panics. 

We can have another one that starts from a valid piece of data

2024-09-30 18:05 UTC, PatStiles commented
> If the data is invalid unmarshall will fatal. Just check the decoding works and doesn't panics.
> 
> We can have another one that starts from a valid piece of data

I split the fuzzer into marshall and unmarshall.

2024-09-30 19:18 UTC, MauroToscano commented
Superseeded by: https://github.com/yetanotherco/aligned_layer/pull/1110

2024-09-30 19:18 UTC, closed without merging